### ISSUE TITLE
skippedTokens in lexer is defined and initialized, but doesn't appear to be used

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#105]
https://github.com/javacc21/javacc21/blob/d04fcf663913276314f504512d34f30da0f69961/src/ftl/java/LexerCode.java.ftl#L108-L109

defines and initializes `skippedTokens` as `private`, but there appears to be no reference to `skippedTokens` anywhere else in the templates (apart from a separate, unrelated use as a local variable in parser recovery routines). Is this lexer field now redundant? Were you planning to use this at some point in the future?

**Comment by revusky** [comment]
I just saw that I never answered this. It is being used in the latest version of the code. However, it is also the case that if we have `regularTokens`, `unparsedTokens`, `moreTokens`, and `skippedTokens`, one of the four is superfluous, I guess, since, for example, if something is not the SKIP, UNPARSED, or MORE set, then it must be a regular (parsed) token. So, in principle, there is only a need to generate 3 of the four sets. However, it's not really a big problem either, so I'm going to close the issue. Oh, also, I think that since you created this issue, I put back in place the DeadCodeEliminator thing, so if something isn't used, it just gets eliminated typically. But, in any case, I don't think there's much of a problem with any of this.

**Comment by vsajip** [comment]
OK, thanks. I'm still a bit hazy on what defines SKIP vs. UNPARSED, though I get the rationale behind MORE.

The `DeadCodeEliminator` is fine for the Java output but not for the other code generation languages, from what I can see. Of course it's not a big issue in and of itself - it's just one field, after all.

**Comment by revusky** [comment]
Well, the distinction betwen UNPARSED (which in legacy JavaCC is SPECIAL_TOKEN) and SKIP has existed since the beginning of JavaCC. A token that is UNPARSED (the so-called "special" token", named rather bizarrely really IMHO) does not participate in parsing. So, if you use the newer Token API and you use something like token.precedingTokens() or token.followingTokens() you can iterate over ALL the preceding or following tokens, including the ones that did not participate in parsing -- and also that, by default, are not added to the AST. So if you traverse the tree recursively, you're not traversing over the unparsed tokens. But then SKIP means that no token at all is created for that run of characters at all. 

As a practical question, SPECIAL_TOKEN (now preferably called UNPARSED) is pretty much always used for comments, while SKIP is pretty much invariably used for whitespace. For the last couple of months, they were synonyms, and it just created a Token object (unparsed obviously) for both comments and whitespace. I just figured it was conceptually simpler if we mapped the entire input file including all the whitespace. And besides, if you iterate over the tokens, it's easy enough to just ignore the types you are not interested in, i.e. whitespace very typically. But then I decided it was a bit wasteful and also just a bit annoying somehow to have all these extra whitespace tokens floating around. So I figured I'd bring back SKIP. In any case, it doesn't even throw away any information, since you can actually get the skipped text before or after a token anyway.

     String skippedText = lexer.getText(tok.getEndOffset(), tok.nextCachedToken().getBeginOffset());

Of course, that will be the empty string if there is nothing skipped between this token and the following one. So, you know, if you really need to do something with the whitespace, you can. I do need to write on the blog explaining all these sorts of things. Here, by the way, is a fairly subtle or tricky point you can get into if you are injecting code into the AST. If you recursively traverse the nodes in an AST, and of course, the tokens are nodes, there is this issue that the next token you traverse in tree walking is not necessarily the one you get via the tok.nextCachedToken() API -- I mean, even taking into account the issue of parsed vs. unparsed tokens. Because, if you injected code into the AST, the next token, from the POV of tree traversal) could be from an injection, while the tok.nextCachedToken() is giving you the next token in terms of the *input file* that it came from. So if you inject a method, a MethodDeclaration node into an AST at the appropriate point, the tree traversal machinery will recurse over the tokens in that injected method, but the previousCachedToken/nextCachedToken is relative to the input file that the token came from and does not "know" about anything that was injected into the AST, right? But this actually makes sense because the tree traversal API and the token chaining API are really operating on two different layers, right?

All of these things need to be explained. Somewhere... The  funny thing is that Tokens were never explained all that well in any docs for legacy JavaCC. If you google it, one of the first hits is this essay called "The TokenManager mini-tutorial" I think, and that surely was written in the late nineties. The thing is that a similar document explaining the token-related APIs for JavaCC 21 would necessarily be much more elaborate because the whole thing is so much more layered (and powerful) now. And frankly, much better designed! Well, the issue I just mentioned above doesn't even exist in legacy JavaCC, because Tokens are not at all integrated into the tree-building, i.e. JJTree. JJTree has no awareness of Token objects at all. It's very strange. They wrote JJTree and created this Node construct, but then never retrofitted the Token API to implement the Node interface. So you can't add Tokens as the terminal nodes to an AST, which is probably the most natural thing imaginable! And, in fact, that is what JavaCC 21 does by default.
