### ISSUE TITLE
Where bin/freemarker.jar comes from?

### ISSUE THREAD

**Issue by vlsi** [javacc21/javacc21#13]
There's a jar file, however, it is not clear where it comes from: https://github.com/javacc21/javacc21/tree/master/bin
Apparently, users would need it as well.

**Comment by revusky** [comment]
Well, in principle, it comes from [here](https://github.com/freemarker/freemarker3). The whole situation is actually quite interesting because, not only does JavaCC21 require FreeMarker to run, but it requires FreeMarker for the build. But that is really  because building JavaCC21 requires JavaCC21! (Which in turn requires FreeMarker.) The plot thickens because if you look [here](https://github.com/freemarker/freemarker3/tree/master/bootstrap) you see that FreeMarker also requires JavaCC21 to be built which in turn requires a bootstrap freemarker.jar to run. So if you were coming at this from that direction, you could again ask where these things "came from"!

Finally, this is maybe akin where the chicken comes from and being told the egg and then asking where the egg comes from and being told it comes from the chicken. It is hard to get one's head around these things but it is actually not really a problem either.

I put out [a release](https://github.com/javacc21/javacc21/releases/tag/v20.02.21) about five minutes ago and you can see that I included a binary, a jarfile, that simply contains the all the freemarker and javacc classes. Finally, I thought that just makes things very simple for people. Of course, that jar could be used to bootstrap the build of either JavaCC or FreeMarker. In any case, people don't really need to worry about where it came from to use it. ;-)

**Comment by vlsi** [comment]
OK. I see it is missing on Maven Central as well. That is unfortunate.

**Comment by revusky** [comment]
This whole thing is an Ersatzproblem.
