### ISSUE TITLE
INDENT and DEDENT tokens

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#139]
At the moment the Python grammar uses `INDENT` and `DEDENT` to mean both token types and `Token` subclasses. This doesn't really work with Python because the name resolution approaches are different in the two languages. As they are 'extra' tokens, I'm not sure how best to arrange that the `Token` subclasses are called e.g. `TokenIndent` and `TokenDedent` so they don't clash.

I have to make `TokenType` constants available as module globals in python so that an unqualified e.g. `IMPORT` in a code block resolves to `TokenType.IMPORT`. This is done in Java by (mis)using an interface, which approach can't be used in Python.

**Comment by revusky** [comment]
Yeah, I see the problem. I guess the issue is with this EXTRA_TOKENS setting that I added. Originally, it did not even create any subclasses of Token, just the TokenType. And then I figured that it would be better to generate the Token subclasses, in particular because I wanted to be able to inject code in there. So my first-pass implementation (which is the current implementation) just creates a Token subclass with the same name as the TokenType.

With token types defined in a regular TokenProduction, you can override the name of the Token subclass, but I didn't put any disposition for that for EXTRA_TOKENS. Possibly something like:

     EXTRA_TOKENS=INDENT#IndentToken, DEDENT#DedentToken;

And that would mean that the name of the Token subclass we generate for INDENT is IndentToken, for example.
