### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#14]
IMHO I think it's very important to have a lot of tests for javacc parser and other future bsupport like fault tolerant.

Writing tests Can take a lot of Time but it's very important

Javacc legacy provide several tests

**Comment by vlsi** [comment]
@angelozerr , I've added a test in https://github.com/javacc21/javacc21/pull/15 :) (see `ArithmeticTest.kt`)

**Comment by revusky** [comment]
Well, I kept most of the old examples from the legacy JavaCC distro around just to use them as test cases. I don't know what tests they introduced recently.

But really, the testing situation is not so bad. One thing to understand is that JavaCC is used to build itself, so the very fact that you can "re-bootstrap", i.e. use the javacc.jar that you just built to rebuild JavaCC again -- this is already, in and of itself, quite a big integrated functional test. Surely it is...  and, to tell the truth, it that test that inspires the most confidence in me. That, and also the ability to use the newer javacc.jar to build FreeMarker and have it pass what tests are set up. I tagged a release today and did all these things beforehand, so I feel it is pretty solid.

What I would like to have, though, is a growing repository of grammars for various languages and we can set up some test suite based on that. I mean, if we had a testsuite where it generated and tested parsers for, let's say... Typescript, PHP, C# and so on and so on, as well as rebuilding FreeMarker... AND rebuilding itself and retesting... you'd start feeling (or at least I would) that you are on pretty solid ground, that if all this is still working, whatever changes you make did not break anything.

Well, when we start getting into fault-tolerant, there is then the question of defining what the expected behavior is and then having tests to make sure that it is behaving as expected.

**Comment by revusky** [comment]
Oh, another strange little fact is that the legacy JavaCC project has the same bootstrap issue. Since JavaCC is used to build itself, they have to include an already built javacc.jar to bootstrap the build. And that is here: https://github.com/javacc/javacc/tree/master/bootstrap

But look at that. Their bootstrap jarfile is 12 years old. I actually just checked and it reports being Version 4.1d1.( I have no idea what the d1 means, but who cares....) That actually tells you, by the way, how dead the project is. There is no way that you would be able to use the current jarfile that I just put up today to bootstrap a build some years from now. That is because, as we add new features, they will inevitably be used internally in the JavaCC grammar itself. And that would mean that you could only bootstrap the build with a fairly recent javacc.jar. The fact that a 12-year-old jarfile can still bootstrap their project means.... well, you can think about it... :-)

**Comment by angelozerr** [comment]
I started to write some tests in https://github.com/javacc21/javacc21/tree/master/src/test/java/com/javacc

We need to improve it but it's a good start.
