### ISSUE TITLE
Newline should reset the column counter, but doesn't

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#140]
This looks wrong:
https://github.com/javacc21/javacc21/blob/1247bf46b537177598a0a0364ebcee4453531b20/src/ftl/java/Lexer.java.ftl#L683-L686
I would say it should be `col = 0;` here instead of the increment.  Of course I can effect this change, but I wanted to run it by you in case you are working on any changes in this area.

**Comment by revusky** [comment]
> This looks wrong:

Yeah, it does. It must have just been some weird short-circuit in my head that caused me to write `++col` instead of `col=0`.

This is actually a fairly major bug, it seems like, and I'm puzzled that the code seemed to have worked anyway. I guess the right indents and dedents were generated anyway or something. As for whether I'm working on this piece of code, no, not really. I actually thought the whole thing was pretty settled and there would be little need to do much with it. Oh well...

**Comment by vsajip** [comment]
Fixed in 0c350a2.
