### ISSUE TITLE
Placement of line in template changed

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#152]
With reference to the fragment
https://github.com/javacc21/javacc21/blob/61eb48a4dfe581c9aefef09ccff1416b3b13cb81/src/ftl/java/Lexer.java.ftl#L292-L297
The last line used to be inside the `[#if]` before the token-chaining changes, but is now outside, even though the comment in the `[#if]` indicates otherwise. If it was deliberately moved out, the `[#if]` could be removed and the comment changed to remove the reference to a lexical state change, as that would only apply if there are multiple states. 

Or should that last line go back inside the `[#if]`?

**Comment by revusky** [comment]
I'm pretty sure the code is correct as it is. Look at: https://github.com/javacc21/javacc21/blob/61eb48a4dfe581c9aefef09ccff1416b3b13cb81/src/ftl/java/NfaData.java.ftl#L82

You see that if we don't have multiple lexical states, the method just returns the nfaData array. (THE nfaData array since there is only one of them) Otherwise, it has to fish out the appropriate one from the table. 

I honestly don't remember what the code looked like before, but this version of it seems correct. Also, it seems correct to just generate the preceding comment if we actually have multiple lexical states, since if we don't, the comment is just confusing.

**Comment by vsajip** [comment]
OK, I just wanted to be sure ...
