### ISSUE TITLE
Could we change this part of the example Java grammar without repercussions?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#156]
In
https://github.com/javacc21/javacc21/blob/5fabe28dc5105616dddb1a4208b25a3ae5a14bdd/examples/java/Java.javacc#L184-L196
rather than defining a private String field in the parser just for this purpose, would it be OK to change it to omit the parser injection and make the `temp` a local variable? As in:
```
 TypeIdentifier#void : 
    <IDENTIFIER>  
    {String temp = getToken(0).getImage();}# 
    ASSERT {!temp.equals("record")  
            && !temp.equals("var")  
            && !temp.equals("permits") 
            && !temp.equals("sealed") 
            && !temp.equals("yield")}# 
           : "Illegal type name " + temp  
    =>|| 
 ; 
```

As far as I can tell, this is the only place where `temp` is used.

**Comment by revusky** [comment]
Yeah, it seems that it can be written more cleanly as you propose. There actually was a reason that I thought it needed to be written this way. It has to do with the production working both in parsing and lookahead. I believed (and it actually seems like my belief was incorrect) that for the code to work in a lookahead routine, the `temp` variable had to be defined at the class instance level. Or actually, it may be that, at a previous point, it had to be, but not any more. You see, the problem would be if the code in the ASSERT was a separate method, then the `temp` variable would not be visible. And maybe that was the case at some point. I honestly can't remember...

But the funny thing about this particular case is that the TypeIdentifier production is not actually used in any scanahead. It is only used in regular parsing, so the `#` is unnecessary and so is the `=>||` at the end, which means to scan ahead to this point when deciding whether to enter this at a choice point. However, the production never occurs at a choice point.

BUT... there is no problem with writing the production based on the assumption that it could be used in a lookahead. What actually happens is that the code generation logic generates a `TypeIdentifier` method for use in regular parsing and a `check$TypeIdentifier` method for use in lookahead, but then it hits the DeadCodeEliminator logic which notices that the latter method is never used and deletes it before generating the final code!

If the production were written in a way that the assertion only applies in parsing, but not a scanahead, then if you did have one of those soft keywords as a type name, it would scan ahead and the lookahead logic would think this was okay, like:

       class record {}

But then when it actually parses that line, it hits the assertion. And that might make perfect sense actually too. Actually, the whole issue with the ASSERT there is my attempt to define things in a maximally correct way. In practice, one would rarely hit this because any Java code that follows current day coding standards, the type names all start with a capital letter anyway!

So, I guess the short answer is that you can rewrite it the simpler way and it can even be written more simply, with the caveat that the production would not work in a lookahead -- or more precisely, it wouldn't check for these soft keywords in a lookahead.

**Comment by vsajip** [comment]
OK, thanks for the background. I've already made that change locally and it seemed to work - I just wanted to make sure there were no other considerations.
