### ISSUE TITLE
Token actions can not affect lexical state switch

### ISSUE THREAD

**Issue by Gravelbones** [javacc21/javacc21#168]
https://github.com/javacc21/javacc21/blob/659a008027ed1e630ce8781564c289264185492f/src/ftl/java/Lexer.java.ftl#L361-L374

If any of these functions changes the tokentype of the matched token, that change does not affect which state the lexer switches to as matchedType is used in the call to doLexicalStateSwitch.
I am unsure whether the token actions should be able to do it, but for now it certainly can't affect it.
If the function should be able to change the state, the call should be doLexicalStateSwitch(matchedtoken.getType()):

**Comment by revusky** [comment]
I didn't get round to answering this, mostly because I was just so totally absorbed in writing that C# grammar. But I was thinking about it. I think your comment is basically correct. There is just this general problem about which "hooks" get activated in which order. For example, if you write a TOKEN_HOOK method, that method could switch lexical states based on potentially much more sophisticated logic than just what the last token type was. So, finally, it seems to me that the TOKEN_HOOK method (or possibly methods in the plural) should be called *after* the doLexicalStateSwitch() that is invoked, not before. In fact, due to your bringing this up, I looked at this more closely and ended up reversing the order in which these things are invoked. This does potentially break somebody's code out there, but I don't think it would happen very often, and I think the way it is now makes more sense. Thanks.

Oh, and if you want to discuss this more, maybe bring it up at https://discuss.congocc.org/

**Comment by revusky** [comment]
Just looking over the open issues. Is there a problem with this now? I think I did something or other, changing the order in which certain things happened. But I mean to say... can this issue be closed now?

**Comment by Gravelbones** [comment]
I just noticed the problem, looking into the code. Since you changed the way it works, I would consider the issue closed.

**Comment by revusky** [comment]
Okay, great. I think your comment that the hooks were being called in the wrong order was correct. But now I'm pretty sure this is addressed.
