### ISSUE TITLE
ParseException in HelloWorld.javacc

### ISSUE THREAD

**Issue by raupachz** [javacc21/javacc21#173]
Hello there,

there is an interesting [article ](https://blogs.oracle.com/javamagazine/post/introducing-the-javacc-21-parser-generator-for-java) about JavaCC 21 in the Java Magazine.

This made me want to play around with JavaCC 21 on this rainy sunday in January.
Here is my very first grammer copied straight from the article.

```
HelloWorld : "Hello" ("," "World")+  <EOF> ;

INJECT HelloWorldParser : {
    static public void main(String[] args) {
       if (args.length == 0) {
           System.out.println("Usage: java HelloWorldParser <input>");
           System.exit(-1);
       }
       String input = "";
       for (String arg : args) input += arg;
       HelloWorldParser parser = new HelloWorldParser(input);
       parser.HelloWorld();
       parser.rootNode().dump();
    }
}
```

Running `java -jar javacc-full.jar HelloWorld.javacc` works. 

Unfortunately there is an issue compiling the *.java files. The java compiler throws an error.

```
HelloWorldParser.java:29: error: unreported exception ParseException; must be caught or declared to be thrown
        parser.HelloWorld();
                         ^
1 error
```

Of course I can easily fix this myself with an try-catch-block in the  INJECT block of the grammar.  I am just not sure if this is intentional.

**Comment by revusky** [comment]
No, this is just a mistake. It wasn't intentional! I honestly don't know whether this was my mistake back when, when I submitted the article or if somebody else made the mistake. In any case, you should just have:

     static public void main(String[] args) throws ParseException {

That should be easy enough. I've been intending to write a couple of more articles since this one was really just a teaser, but I had some health problems late summer that sort of threw me for a loop. And then, on recovering, I got totally absorbed in other things.

Anyway, thanks for the head-up.

**Comment by raupachz** [comment]
Hi @revusky 

thanks for the quick response. No worries, I am glad you feel better. I am only paying around and this was just a minor issue. Just thought it would be good to mention here.

Keep up the good work! Thank you for working on this.
