### ISSUE TITLE
CodeInjector has duplicates in the "implementsLists" mapping.

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#178]
This image shows what I mean:
![ss1](https://user-images.githubusercontent.com/130553/162193825-c12c67a0-025f-47b6-a0e9-ab90e3d57889.png)
This is when processing the C# grammar.

**Comment by revusky** [comment]
Well, it looks like the line with "implements Expression" is repeated. https://github.com/javacc21/javacc21/blob/master/examples/csharp/CSharp.javacc#L891

It doesn't seem offhand like this should really cause a problem, since the things that a Node implements should be a set and not care about repetitions. But I guess that must be the problem, no?

**Comment by vsajip** [comment]
I agree that it should be  a set, but it's currently implemented as a list. Not sure why one repetition results in 7 entries in the list! I'll remove the duplicated line and see what happens.

**Comment by vsajip** [comment]
This has been implemented as part of #221.
