### ISSUE TITLE
A problem with Parser constructor which takes a reader?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#183]
I made a change to the `CSParse` class in `examples/csharp`, to demonstrate a possible problem. I replaced the `parseFile` method with this:
```java
   static public void parseFile(File file, boolean dumpTree) throws IOException, ParseException {
       CSharpParser parser;

       if (System.getenv("CSPARSE_READER") == null) {
           parser = new CSharpParser(file.toPath());
       }
       else {
           FileInputStream fis = new FileInputStream(file);
           InputStreamReader isr = new InputStreamReader(fis, StandardCharsets.UTF_8);
           Reader reader = new BufferedReader(isr);
           parser = new CSharpParser(reader);
       }
       Node root=parser.CompilationUnit();
       if (dumpTree) {
           root.dump("");
       }
   }
```
The change is to construct the parser using a `Reader` when the `CSPARSE_READER` environment variable is defined, otherwise construct it using a `Path` as before. The parser constructor with a `Path` works, but the one constructed with a `Reader` doesn't:
```
$ java CSParse testfiles/Interop.VARIANT.cs 
(.. correctly dumped AST elided)
  EOF
Parsed testfiles/Interop.VARIANT.cs in 758.1 milliseconds.
```
As opposed to:
```
$ CSPARSE_READER=1 java CSParse testfiles/Interop.VARIANT.cs 
Error processing file: testfiles/Interop.VARIANT.cs
org.parsers.csharp.ParseException: 
Encountered an error at (or somewhere around) input:1:1
Was expecting one of the following:
INTEGER_LITERAL, REAL_LITERAL, FALSE, TRUE, NULL, LPAREN, LBRACKET, SEMICOLON, BANG, TILDE, INCR, DECR, PLUS, MINUS, STAR, BIT_AND, HAT, RANGE, ABSTRACT, BASE, BOOL, BREAK, BYTE, CHAR, CHECKED, CONST, CONTINUE, DECIMAL, DEFAULT, DELEGATE, DO, DOUBLE, EXTERN, FIXED, FLOAT, FOR, FOREACH, GOTO, IF, INT, INTERNAL, LOCK, LONG, NEW, OBJECT, OVERRIDE, PRIVATE, PROTECTED, PUBLIC, READONLY, REF, RETURN, SBYTE, SEALED, SHORT, SIZEOF, STACKALLOC, STATIC, STRING, SWITCH, THIS, THROW, TRY, TYPEOF, UINT, ULONG, UNCHECKED, UNSAFE, USHORT, USING, VIRTUAL, VOID, WHILE, ASYNC, AWAIT, NAMEOF, PARTIAL, YIELD, IDENTIFIER, CHARACTER_LITERAL, REGULAR_STRING_LITERAL, VERBATIM_STRING_LITERAL, REGULAR_INTERPOLATION_START, MULTI_INTERPOLATION_START, LBRACE, DYNAMIC
Found string "﻿" of type INVALID
	at CSharpParser.Statement(CSharp.javacc:770)
	at org.parsers.csharp.CSharpParser.Statement(CSharpParser.java:14415)
	at CSharpParser.CompilationUnitBody(CSharp.javacc:41)
	at org.parsers.csharp.CSharpParser.CompilationUnitBody(CSharpParser.java:560)
	at CSharpParser.CompilationUnit(CSharp.javacc:33)
	at org.parsers.csharp.CSharpParser.CompilationUnit(CSharpParser.java:503)

Parse failed on: testfiles/Interop.VARIANT.cs
```
Any ideas on what might be going wrong?

**Comment by revusky** [comment]
I think the problem is that the testfile you're using (maybe all of them in that testfiles directory for CSharp) use this BOM, the byte order mark at the start of the file to indicate the encoding. That's described [here](https://docs.microsoft.com/es-es/globalization/encoding/byte-order-mark). The initial bytes in the file are used to indicate the encoding.

So, you see that the [stringFromBytes method](https://github.com/javacc21/javacc21/blob/master/src/ftl/java/Constants.java.ftl#L128-L160) peaks at the initial bytes of a file to see if it is a BOM. (It's true that this seems to be almost exclusively a Microsoft thing, but finally I just had it *always* check for the BOM when reading in a file because the objective likelihood of that byte sequence starting a file *by accident* is just about nil...)

Anyway, the reason that passing in the Reader does not work in this instance is that it's not taking into accoun the BOM. Now, I'm a bit confused and not certain whether this is a bug because if you pass in a java.io.Reader to the constructor, I guess it should assume that it's getting a stream of char to parse so the BOM logic should already have been taken care of because all fo the byte to char conversion was already taken care of presumably and that would include the initial BOM bytes. You see what I mean?

Finally, I would point out that the constructors that take a Reader are marked as deprecated. (I don't remember when I did that.) So, certainly, by the time we've switched to the Congo naming, we should just get rid of all the deprecated constructors. Really, I think that the main constructor to an XXXParser should just take a String (or more precisely a CharSequence) but also we should support passing in a java.nio.path.Path object since that is the more modern API for a filename. (And you can use java.io.File perfectly well, since you just pass in file.toPath()). I mean, it's just too common that you want to pass in a file name, s we should provide that convenience.

But it seems that, strictly speaking, the code that takes a Reader is doing what it should because all the byte->char conversion is presumably already handled at this point including the BOM. In theory, I guess... But anyway, in terms of answering your question about what is going on, I think the above is the answer!

**Comment by vsajip** [comment]
Oh, I forgot about the BOM :grimacing: , here, thinking that the Java libraries would handle it transparently (in the Python code, I handle the BOM explicitly. Since Python allows the encoding to be specified in the first couple of lines of source, I have to [open the file as binary and deal with BOM and encoding](https://github.com/javacc21/javacc21/blob/c230ba7792964328c41549ae126a18480c39b22b/src/ftl/python/lexer.py.ftl#L340-L371)).

> Finally, I would point out that the constructors that take a Reader are marked as deprecated. (I don't remember when I did that.) So, certainly, by the time we've switched to the Congo naming, we should just get rid of all the deprecated constructors.

Yep, agreed.
