### ISSUE TITLE
Incorrect line numbers in stack trace

### ISSUE THREAD

**Issue by hylkevds** [javacc21/javacc21#187]
Stack traces contain these cool references to the source of the parser, but currently they are always pointing to line 1:

```
Exception in thread "main" ex1.ParseException: 
Encountered an error at (or somewhere around) input:1:1
Was expecting one of the following:
A
Found string "b" of type B
	at ex1.Calc.handleUnexpectedTokenType(Calc.java:465)
	at ex1.Calc.consumeToken(Calc.java:454)
	at ex1.Calc.FindA(Calc.java:292)
	at Calc.FindAB(test.ccc:1)
	at ex1.Calc.FindAB(Calc.java:235)
	at Calc.Start(test.ccc:1)
	at ex1.Calc.Start(Calc.java:193)
```

Looking at the code, it seems the parser puts an offset on the stack:
```
            pushOntoCallStack("FindAB", "test.ccc", 167);
```
But in the trace it seems to compare this offset to the _parsed input_ instead of the source code file:
```
        StackTraceElement createStackTraceElement() {
            return new StackTraceElement("Calc", productionName, sourceFile, getLine());
        }
```
```
        final int getLine() {
            return getTokenSource().getLineFromOffset(offset);
        }
```
The getLine goes to the Lexer, which uses the input, not the source.

I know it once worked, since your example in https://github.com/javacc21/javacc21/issues/43 shows

**Comment by revusky** [comment]
Yes, you're right about where the bug is. And it also seems that this has not been working for two months (!) which is kind of embarrassing. Well, the thing is that the project has not been very active over the last few months, so normally this would have been detected and fixed much faster, I daresay.

The bug is since commit b1f7d745478871b101c795e2008b970b29c739f9 and for now, I just reverted the problematic changes.

**Comment by revusky** [comment]
Yes, your diagnose of the problem is quite correct. I thought that I could store the offset in the call stack but when it converts the offset to the line number, it is using the line map of the parsed input, NOT the grammar! So the line numbers in the stack trace end up being completely wrong. I introduced this bug 2 months ago.

I mean, in terms of the ongoing conversation about stability/reproducibility, well, you can look at this from two perspectives. Yes, it is true that there can be new bugs in the newer version, and this is an example of that, but insisting that people use the latest version if they want support is precisely what allows the bugs to be found and nailed quite quickly. So... the whole issue is actually not so simple...

**Comment by hylkevds** [comment]
Yep, line numbers are back :)
