### ISSUE TITLE
I'd like to move this code to Lexer.java.ftl, as it doesn't contain anything specific to a grammar - any objections?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#205]
https://github.com/javacc21/javacc21/blob/db8c700b43c1f02039bafc2a5b2998306ca06ee7/src/ftl/java/Constants.java.ftl#L38-L175

**Comment by vsajip** [comment]
This is a tracking issue to be closed when I've moved the code.

**Comment by revusky** [comment]
Oh, go right ahead and move the code. I think this is surely a vestige of when there was a `USER_DEFINED_LEXER` option, so if you wanted something to always be available, you couldn't put it in the XXXLexer, because if the user defined their own lexer (though I really don't know how many people ever did that!) then no lexer was generated. But now the XXXlexer is always generated so it's not an issue.
