### ISSUE TITLE
Some good practice for code

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#22]
@revusky as you are refactor a lot javacc, I suggest you to follow those rules:

Take a sample with 

```java
private List<TokenProduction> tokenProductions = new ArrayList<>();
```
in 

https://github.com/javacc21/javacc21/blob/b8b3f270a4f93109484c8b7d9d88b518b0343eb3/src/main/java/javacc/Grammar.java#L65

I suggest you:

 * set in final the list
 * create the ArrayList in the constructor. When you debug step by step the code, the debugger keep in the constructor of the class for each fields and don't jump from fields to fields.

So the idea is to have that:

```java
private final List<TokenProduction> tokenProductions;

...

  public Grammar(JavaCCOptions options) {
...
    this.tokenProductions = new ArrayList<>();
}
```

**Comment by revusky** [comment]
This has been an open issue now for over a year and I'm just going to close it.

I simply do not believe that this is such a clear "best practice". Or certainly there is nothing wrong with having:

    List<Foo> fooList = new ArrayList<>();

at the top level of a class definition. To do it the way you propose does not offer me any advantage and it strikes me as somewhat less readable. (Maybe just a bit, but still...) As things stand, I see in one glance, without going to any other point in the code, that the variable is instantiated to an empty list, specifically an ArrayList (it could be LinkedList or something but it isn't) and I see that without jumping anywhere else in the code!

But the real problem here is that I have to say frankly that if you're not going to do any meaningful work in the code yourself, you really shouldn't be trying to impose your own arbitrary coding standards. If, at some future point in time, you were to *take ownership* of big pieces of the code (and that would be great!) then you could write such things the way you prefer to write them. And, since you would be the one doing the work, I wouldn't express any opinion on it. Certainly not on something of this level of marginal importance. So... *ça y est*

(But it's no big deal really. I just see all this backlog of open issues and just want to close them.)
