### ISSUE TITLE
Lookahead predicate code block is lost

### ISSUE THREAD

**Issue by adMartem** [javacc21/javacc21#228]
For the following parser the `isTrue()` code block for the second ("begin") choice is not generated in lookahead, but the predicate is correctly generated in the first ("immediate") choice. I think it is a bug.  

```
BASE_SRC_DIR="../../../src-generated/congocc/java/test";
NODE_DEFAULT_VOID=true;

INJECT PARSER_CLASS :
{
    boolean isTrue() { // in the real parser this method conditionally scans/consumes tokens 
        return true;
    }
}

ExecSql : 
    "exec sql"
    ( SqlExecuteStatement =>|| | Bar )
    "end-exec"
;

SqlExecuteStatement : 
    "execute"  
    (
        "immediate" (  Foo  |  {isTrue();}#  )
        |
        "begin" {isTrue();}#
    )
;

Foo :
    "foo"
;

Bar :
    "bar"
;
```

**Comment by revusky** [comment]
You're right. That's a bug. The problem, as you may have realized, is this recurring issue of the `isSingleToken` logic. The first choice with "immediate" consumes 2 tokens while the second choice with "begin" consumes *exactly* one token so there was a little bug where it thought it could get away with just doing `scanToken` and wasn't generating the `isTrue()` Java snippet.

Well, anyway, that is fixed now, I'm pretty sure. The fix was really quite trivial. You might find it instructive to look at. https://github.com/javacc21/javacc21/commit/b641d4139b0834e82a59066fd75ed467524bec4a

**Comment by adMartem** [comment]
Actually, I hadn't realized that.  That was one workaround path I didn't try.  Anyway, it is indeed fixed now.  Thanks!
