### ISSUE TITLE
ASSERT lookahead inside OneOrMore (and probably ZeroOrMore)

### ISSUE THREAD

**Issue by adMartem** [javacc21/javacc21#234]
In my grammar, 
1. `( SCAN Identifier [ <COMMACHAR> ] ASSERT ~(AssignmentOperator) => Identifier [ <COMMACHAR> ] )+ `
works, but
2. `( Identifier [ <COMMACHAR> ] ASSERT ~(AssignmentOperator) =>|| )+`
doesn't.

What appears to be the problem in 2 is that in its check$ (lookahead) the ASSERT causes its check to FAIL in the `while` loop, setting hitFail and then returning `true` for the OneOrMore's lookahead.  But hitFailure remains `true`.  I think that causes the entire higher-level lookahead to eventually fail erroneously.  I can't easily debug it due to my parser being more than 64K lines, but that seems to be the case.

I didn't examine the generated code in detail for the similar case of
3. `Identifier ( [ <COMMACHAR> ] Identifier ASSERT ~(AssignmentOperator) =>|| )* `
which I also tried along the way.  It also failed.  

Here is the referenced code snippet:
```
// BuildProductionLookaheadMethod macro
    private final boolean check$IdentifierList() {
        if (hitFailure||remainingLookahead<=0) return!hitFailure;
        // Lookahead Code for OneOrMore specified at /Users/jmb/Development/Local_Repositories/p3cobol/src/main/congocc/p3cobol.ccc:7989:5
        if (!check$p3cobol_ccc$7989$7()) {
            return false;
        }
        while (remainingLookahead> 0&&!hitFailure) {
            Token token40484= currentLookaheadToken;
            if (!check$p3cobol_ccc$7989$7()) {
                currentLookaheadToken= token40484;
                break;
            }
        }
        return true;
    }
…
// scanahead routine for expansion at: 
    // /Users/jmb/Development/Local_Repositories/p3cobol/src/main/congocc/p3cobol.ccc:7989:7
    // BuildScanRoutine macro
    private final boolean check$p3cobol_ccc$7989$7() {
        try {
            lookaheadRoutineNesting++;
            // BuildPredicateCode macro
            if (remainingLookahead<=0) return true;
            if (hitFailure||remainingLookahead<=0) return!hitFailure;
            // Lookahead Code for NonTerminal specified at /Users/jmb/Development/Local_Repositories/p3cobol/src/main/congocc/p3cobol.ccc:7989:7
            // NonTerminal Identifier at /Users/jmb/Development/Local_Repositories/p3cobol/src/main/congocc/p3cobol.ccc:7989:7
            pushOntoLookaheadStack("IdentifierList", "/Users/jmb/Development/Local_Repositories/p3cobol/src/main/congocc/p3cobol.ccc", 7989, 7);
            boolean prevScanToEnd36050= scanToEnd;
            currentLookaheadProduction= "Identifier";
            scanToEnd= true;
            ++nonTerminalNesting;
            try {
                if (!check$Identifier()) return false;
            }
            finally {
                popLookaheadStack();
                scanToEnd= prevScanToEnd36050;
                --nonTerminalNesting;
            }
            if (hitFailure||remainingLookahead<=0) return!hitFailure;
            // Lookahead Code for ZeroOrOne specified at /Users/jmb/Development/Local_Repositories/p3cobol/src/main/congocc/p3cobol.ccc:7989:18
            Token token36051= currentLookaheadToken;
            if (!scanToken(COMMACHAR)) currentLookaheadToken= token36051;
            if (hitFailure||remainingLookahead<=0) return!hitFailure;
            // Lookahead Code for Assertion specified at /Users/jmb/Development/Local_Repositories/p3cobol/src/main/congocc/p3cobol.ccc:7989:34
            if (check$p3cobol_ccc$7989$43()) {
                hitFailure= true;
                return false;
            }
            if (!scanToEnd&&lookaheadRoutineNesting<=1&&nonTerminalNesting<=1) {
                remainingLookahead= 0;
            }
            return true;
        }
        finally {
            lookaheadRoutineNesting--;
        }
    }
```

**Comment by revusky** [comment]
I think this is fixed, though I'm less certain than the last few times I said something was fixed, because I never constructed a test case.

I'm pretty sure the problem is as you diagnosed. An assertion failing *in a scanahead* was propagating beyond where it should. So, if you have:

      ("foo" "bar" ASSERT {someCondition()}# =>||)+

then the lookahead routine that checks whether to repeat the loop should check whether the next two tokens are "foo" followed by "bar" and then whether `someCondition()` is satisfied. If that is the case, we repeat the loop, and if not, we break out. Of course, a key point, which I guess you do understand is that assertions in JavaCC21 are actually more nuanced than in regular programming languages. If an assertion fails in regular parsing, it just aborts basically (well, it throws a ParseException which *might* be caught and handled somehow, but basically from the local point of view, just aborts...). And that's like an assertion in Java or any programming language typically. But if an assertion fails in a scanahead routine, this is just taken to mean that the lookahead returns false.

And, of course, if we had instead:

     ("foo" "bar" =>|| ASSERT {someCondition()})+

then if the assertion fails, it's failing in the parsing stage, so it's throwing a ParseException and probably just aborting.

But anyway, I'm pretty sure the problem you're hitting (*yes, a bug*) is that the assertion failure was propagating upwards when it shouldn't. So the lookahead for the enclosing expansion was taken as having failed, when it should just be the lookahead for just the inner loop.

As for the `OneOrMore` vs. `ZeroOrMore`, I guess it's basically understood that:

      (Foobar)+

is just a more terse way of writing:

      Foobar (Foobar)*

(If there is somehow a case where the above two are not the same, i.e. behave differently, this is surely a bug!)

So, if lookahead code is generated for whether to loop, it is only run starting from the second iteration in a `OneOrMore`. The first iteration is unconditional.

By the way, I write the above as much for myself as for you. I was thinking about all this earlier today and managing to get confused! But regardless, I think this is okay now.

**Comment by adMartem** [comment]
It now works for my test cases.  Thanks once again. 

If you are curious, the case that this production is dealing with is the following (in COBOL):
`move 1 to a b = 2`.
The assignment statement `b = 2` is an extension in some dialects synonymous with `compute b = 2`, which introduces the issue.  It has to be differentiated from `move 1 to a b ...` that moves 1 to both a and b.  Another extension affecting this is the allowance of `move 1 to a,b,c,d ...` in many dialects, hence the COMMACHAR token that only will exist when there is a "," not followed by a " " (space) forming the proper way to use the so-called comma space separator.  The "correct" way in COBOL to write this is `move 1 to a, b, c, d ...` (spaces after the commas) due to COMMACHAR's potential use as the decimal separator.  So in this case the ZeroOrMore form of the production (number 3) is actually more correct for resolving this particular COBOL quirk, which is why I tried it in my flailing about, hoping it might accidentally make the problem go away only to find it failed too.  I ended up with number 1 as my short-term workaround.
