### ISSUE TITLE
Parsing problem with \"

### ISSUE THREAD

**Issue by p-muessig** [javacc21/javacc21#245]
I'm porting an JavaCC 5.0 project to JavaCC 21 and noticed a parsing problem with \\".

Grammar file "asl.javacc":
```
FAULT_TOLERANT;
MINIMAL_TOKEN;
SMART_NODE_CREATION = false;
JAVA_UNICODE_ESCAPE = false;
NODE_PACKAGE = "org.example";
PARSER_PACKAGE = "org.example";
UNPARSED_TOKENS_ARE_NODES;

SKIP : " " | "\t" | "\n" | "\r" | "\f" ;

UNPARSED :
      <LINK_START : "<a href=\"" <LINK> "\">">
//      <LINK_START : "<a href='" <LINK> "'>">
    | <#LINK : "SCRIPTIO_" ( "IN" | "OUT" ) "PUT" ( ["0" - "9"] )+>
    | <LINK_END : "</a>">
    ;

TOKEN :
      <GT : ">">
    | <NAME :
        ~["0"-"9", "'", "\"", "<", ">", ",", "(", ")", ";", "[", "]", "!", "=", "\n", "\r", "\t", ".", " ", "/", "+", "-", ":", "^", "$", "*", "?"]( ~["'", "\"", "<", ">", ",", "(", ")", ";", "[", "]", "!", "=", "\n", "\r", "\t", ".", " ", "/", "+", "-", ":", "^", "$", "*", "?"])*
      >
    ;

Foo : <NAME> <EOF> ;
```
Main.java:
```
package org.example;

import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;

public class Main {
    public static final String TEXT = "<a href=\"SCRIPTIO_OUTPUT4\">output</a>";
//    public static final String TEXT = "<a href='SCRIPTIO_OUTPUT5'>output1</a>";

    public static void main(String[] args) throws IOException {
        try (Reader reader = new StringReader(TEXT)) {
            AslParser parser = new AslParser(reader);
            parser.Foo();
            Node root = parser.rootNode();
            root.dump();
        }
    }
}
```
Parsing then produces
```
<Foo (1, 27)-(1, 37)>
  > (incomplete)
  output
  EOF
```
When using ' instead of \\" parsing works correctly.

**Comment by revusky** [comment]
Thanks for reporting this. It was a rather strange bug. It was in this messy routine `removeEscapesAndQuotes` that had some incorrect logic in it. I'm rather befuddled that a bug in a routine like that could survive so long. It must have been there forever, but I guess it's only a few corner cases where it showed itself. Actually, I eyeballed the method for a long time and couldn't even figure out where it was, so I finally just tore it up and rewrote the method.

By the way, you can write your main() above as:

    public static void main(String[] args) {
         AslParser parser = new AslParser(TEXT);
         parser.Foo();
         Node root = parser.rootNode();
         root.dump();
     }

For the past year at least JavaCC 21 basically just dispenses with all this buffered reader sort of thing. And the base API just takes a String (or stringy sort of object as its input parameter.) So all that stuff of wrapping your input string in a `StringReader` is needless because internally, the constructors that take a `Reader` just suck everything in anyway, so you might as well just use the constructor that takes a string (or any stringy sort of object actually, anything that implements `CharSequence`). And now, by default, `ParseException` is an unchecked exception, just extends RuntimeException so no need for any try blocks.

I also realized one thing rooting out this bug. It's easier to debug this kind of problem turning `FAULT_TOLERANT` off!

Anyway, pick up the latest version and try it again. Thanks.

**Comment by revusky** [comment]
Hi Peter. Largely as a result of this bug report, I finally decided to scratch a certain itch, as you can see here:

https://discuss.congocc.org/d/17-ann-you-can-now-use-single-quote-strings-in-regexp-specifications

So, now the line here:

    <LINK_START : "<a href=\"" <LINK> "\">">

can be written more readably as:

    <LINK_START : '<a href="' <LINK> '">' >

I think the ability to avoid escaping the double-quotes like that will be less error-prone. (For ME anyway!)

So, if you get the latest version, this should be available. I think this is pretty orthogonal to anything else, but if you run into any issues, by all means, tell us about it.
