### ISSUE TITLE
support for optional tokens?

### ISSUE THREAD

**Issue by wumpz** [javacc21/javacc21#25]
Does your version of JavaCC / fork (I don't know how to name it) support optional tokens. I use heavily JavaCC within my project. One problem I had to deal with was to change some token processing by flag. 

Here is an SQL example. 

SQLServer allows bracket quotation of object names, like

    select * from [mytable]

This does the same as double quotes by the way. So other databases use this brackets for array expressions, like

    select a[5] 

and this **5** could be a complete expression or a column name the index comes from. But for SQLServer this **5** would be a perfectly valid column alias.

So the user should decide, which way to go. There was a huge discussion going on with different solutions to this problem: from multi grammars, to token type rewrite.

https://github.com/JSQLParser/JSqlParser/issues/677

So the working solution first reads the quoted object name type and uses then the following java code to skip this and proceed to array processing:

    { if ( !allowSquareBracketQuotation && matchedToken.image.charAt(0) == '[' ) {
         matchedToken.image = "[";
         for (int i=0;i<CCJSqlParserConstants.tokenImage.length;i++) {
            if (CCJSqlParserConstants.tokenImage[i].equals("\"[\"")) {
                matchedToken.kind = i;
            }
         }
         input_stream.backup(image.length() - 1);
       }
    }

**Comment by revusky** [comment]
> Does your version of JavaCC / fork (I don't know how to name it)
 
LOL. Yes, I have the same terminological issue, since the term "fork"  implies (in this case, falsely) that there is another (or possibly more than one other) branch of development. But there isn't. It's really not "my fork of JavaCC" but just "my continuation of work on JavaCC".

> support optional tokens. 

Yeah, okay, to get to your actual question.... Well... I looked at this situation and, as far as I can see, in this case, there isn't any additional feature of JavaCC 21 that really deals with this case. Or, in other words, the solution would, as far as I can see, be the same in JavaCC 21 as legacy JavaCC.

What I think you need to do is to have the "[" correspond to 2 different token types. The way to do that would be to define another lexical state (a phony lexical state) for the second "[" token type. By a phony lexical state, I mean one which you never actually enter, but exists in order to define some extra tokens.

So, in your default lexical state you might have:

<OPEN_BRACKET : "[">

and then in your "phony" lexical state, you have something like:

<PHONY> TOKEN: {<BRACKET_USED_AS_QUOTE : "[" >}

Then, in your CommonTokenAction method, you could change the OPEN_BRACKET token type into a BRACKET_USED_AS_QUOTE type (though obviously you need something maybe a bit kludgy in there to check which case it is, but that is your problem obviously!) but then in your grammatical productions, you just treat this cleanly as two different token types and thus, two different grammatical productions probably.

But, as best I can see, that is the solution (at least what I would go for) whether using JavaCC 21 or legacy JavaCC. Actually, you can see that this is what I did in FreeMarker. https://github.com/freemarker/freemarker3/blob/master/src/parser/FM.javacc#L654

And  you can see where this "phony" token type DIRECTIVE_END is referenced in a CommonTokenAction here: https://github.com/freemarker/freemarker3/blob/master/src/parser/FM.javacc#L253

That FreeMarker grammar, by the way, is for JavaCC 21, so you see there TokenType.DIRECTIVE_END, which in JavaCC 21 is not an integer, but a typesafe enum. Well, I mean to point out that the API's have evolved towards more modern Java code. So JavaCC 21 doesn't have all this direct access to fields, so it's token.setType(TokenType.DIRECTIVE_END) as opposed to token.kind = DIRECTIVE_END.

BUT... that said, the basic solution was put in place way back when FreeMarker just used Legacy JavaCC, so the outline of the solution I give you above doesn't really have much to do with using JavaCC 21 specifically. I just point out that with JavaCC 21, there is some adjustment to the client code because we got rid of all this direct access to public fields.

Well, there, I'm veering into TMI, so I guess I should end this note here.

Anyway, thanks for getting in touch and if there's anything I can help with, answering questions about a migration to JavaCC 21, feel free to ask. Well, in summary, the bottom line for this specific case is that the solution using JavaCC 21 would be basically the same. There are plenty of other cases, however, where features present in JavaCC 21 would allow a far more elegant solution than legacy JavaCC. This doesn't seem to be one of them though!

**Comment by wumpz** [comment]
So thx for this litte scenic excursion ... Now I have more to think about ... 

By the way, could you tell me something about how performance compares between javacc21 and javacc (legacy)? A long time ago I considered a switch to ANTLR 4 but the performance comparison of ANTLR 4 to JavaCC was devastating for ANTLR 4.

https://github.com/JSQLParser/JSqlParser/wiki/What-would-be-the-benefit-of-switching-to-ANTLR-4-as-a-parser-generator%3F

and

https://github.com/JSQLParser/JSqlParser/issues/557

**Comment by revusky** [comment]
> So thx for this litte scenic excursion ... Now I have more to think about ...
> 
> By the way, could you tell me something about how performance compares between javacc21 and javacc (legacy)? 

Well, I think the bottom line is that this is not really an issue. I'm pretty sure you won't find any noticeable difference.

Now, to be absolutely open and honest, it is probably the case that JavaCC21 generated parsers are a little bit slower because, you see, JavaCC was originally written in the nineties by people who were C hackers with that kind of mentality, so the code has practically no concept of encapsulation, say. Just direct field access all over the place. So, you know, having code that is better structured, with better encapsulation, you have a bit more indirection, the implementation encapsulated behind the API.... and there is some cost to that, but it is unlikely to be very important. (But ANTLR Is a totally different story! LOL!)

If you want to try something a bit fun, try this... on the command-line:

```
git clone https://github.com/javacc21/javacc21.git
cd javacc21
ant
cd examples/java
ant test
```

And then if you want to unleash the parser on any tree of java source code, it's just
`java JParse <directory>`

On my work machine (nothing specia)l it runs over the entire JDK 8 source code (the src.zip unzipped somewhere) in a bit over 10 seconds. (And that's with tree building enabled...)

The same benchmark using the Java 8 grammar included with ANTLR takes the better part of an hour (!) I went out, got some lunch, came back and the thing was still running! Amazing!

> A long time ago I considered a switch to ANTLR 4 but the performance comparison of ANTLR 4 to JavaCC was devastating for ANTLR 4.

Yeah, I was amazed. You know, that Italian guy, Federico Tomassetti, I sent him the results of the benchmark (because I had some correspondence with him) and he just shrugged it off. Told me the same thing he apparently told you, that the great Terence Parr says that you can optimize the ANTLR grammar and... But this is a 200x (maybe closer to 300x actually....) difference in speed and that was the Java grammar that comes with ANTLR! And besides that, you know, the Java grammar that I have in JavaCC 21 (recently tweaked to handle up to JDK 13) I've done absolutely *nothing* to optimize it. Nothing. I was just concerned with it working correctly!

But that Federico is... well... not quite normal. The last message he ever sent me in private, he told me never to write him again, because I had insulted both him and Professor Parr. (That's nonsense, of course.) He's some kind of ANTLR/Terence Parr fanboy or something... Some kind of head case... But telling me that performance is not so important when I tell him that ANTLR runs the same benchmark 200x slower.... Sheesh...

> 
> https://github.com/JSQLParser/JSqlParser/wiki/What-would-be-the-benefit-of-switching-to-ANTLR-4-as-a-parser-generator%3F
> 
> and
> 
> [JSQLParser/JSqlParser#557](https://github.com/JSQLParser/JSqlParser/issues/557)

Yeah, that's our Freddy boy!

> 
> However, there are some useful tools in ANTLR 4 like **automatic operator precedence**, which comes in handy. But this could be one reason, that it takes more time.

Well, maybe, but it's hard to imagine that causing such a slowdown. Actually, if I had to guess, I would say it's the lexical scanning must be vastly slower. Mostly that. Because I can't see where you'd get this 200x difference on the straight parser side. But I've never looked into it. There was a Javaworld and they wrote a JSON parser using JavaCC and ANTLR and JSON is very straightforward, not so many different ways to write it, and they benchmarked the JavaCC parser at 40x faster.

Well, I could add that my benchmark, where ANTLR was hundreds of times slower... well... that's over the entire JDK 8 source code. I also did the benchmark on some smaller sets of code and the difference was more like the 40x difference from the Javaworld article. I figured that there are certain files (heavy in certain constructs that it's slow on) that are really slowing it down, so on those specific files, which would not be hard to narrow in on, the thing must be literally 1000x slower (or worse.) It would maybe not be so hard to get to the bottom of this, but I didn't explore further. 

All of that did serve to reassure me that my further work on JavaCC really did have some value. COmputers have got a lot faster and all that, but just to give up more than 2 decimal orders of magnitude of speed...

**Comment by revusky** [comment]
You know, the feature that JavaCC 21 has that your project could probably get the most benefit out of is [INCLUDE](https://doku.javacc.com/doku.php?id=include). If you're supporting multiple SQL dialects, you could probably just have a base SQL-common grammar and INCLUDE it in the various other grammars.

Here, for example, is what the JSONC (JSON with comments) grammar that is included with JavaCC 21 looks like: https://github.com/javacc21/javacc21/blob/master/examples/json/JSONC.javacc

I don't know SQL that well, but I imagine there are some variants of SQL that only differ from the common base, let's say, in one or two minor respects, so you could just have a very trivial grammar in some cases, right?

**Comment by revusky** [comment]
> [JSQLParser/JSqlParser#677](https://github.com/JSQLParser/JSqlParser/issues/677)
> 
> So the working solution first reads the quoted object name type and uses then the following java code to skip this and proceed to array processing:
> 
> ```
> { if ( !allowSquareBracketQuotation && matchedToken.image.charAt(0) == '[' ) {
>      matchedToken.image = "[";
>      for (int i=0;i<CCJSqlParserConstants.tokenImage.length;i++) {
>         if (CCJSqlParserConstants.tokenImage[i].equals("\"[\"")) {
>             matchedToken.kind = i;
>         }
>      }
>      input_stream.backup(image.length() - 1);
>    }
> }
> ```

I realize that this conversation was about 5 months ago. My responses were really quite wooly-headed. 

The long and short of this is that this whole problem of context-dependent tokens is just about completely intractable in JavaCC (AND in JavaCC21 until less than a week ago!)

Like the code you post here, I can't honestly say I really understand it out of context, but the overarching problem is that this sort of thing cannot really provide a satisfactory solution using legacy JavaCC. The reason has to do with the interaction of syntactic lookahead with the token stream. Once the lookahead tokens are cached, the `CommonTokenAction` hook never gets to revisit them, you see, so once you've tokenized based one assumption, you're kind of stuck. The solutions to this involve very inelegant hacks that are not going to be very robust.

The real point here is that JavaCC21 now does have the basic machinery to handle this sort of problem correctly. That is very recent though and I document it [here](https://javacc.com/2020/10/20/context-sensitive-tokenization/). If you have any questions or comments about this stuff, my preference is to have the conversation on the [Discourse forum I've set up.](https://parsers.org/t/you-cant-get-there-from-here-the-problem-of-context-sensitive-tokenization/78) though I suppose I won't be that strict about it. It's just that I want to foment some activity there.

Anyway, have a look.... There are some refinements in the pipeline, but the machinery is now in place to deal with this problem when it wasn't there before.

**Comment by revusky** [comment]
I think that this [latest feature described here](https://javacc.com/2021/06/13/activating-de-activating-tokens/) does really nail this issue. 

If this does not solve the problem that this issue was opened for, by all means tell me so, or tell me something... since you are the one who opened the issue... In particular, this may be just one part of an overall set of things that finally makes these sorts of problems tractable: [having a preprocessor](https://javacc.com/2021/02/01/javacc-21-has-a-preprocessor/) along with the ability to break the grammar apart with [includes](https://doku.javacc.com/doku.php?id=include). This provides some real tools to solve these problems on a fundamental level. But maybe you guys are masochists and thus, not interested...
