### ISSUE TITLE
Override parser rules

### ISSUE THREAD

**Issue by timbault** [javacc21/javacc21#26]
Hi,

i am writting a grammar and i am using the INCLUDE feature.

Let's say i have two grammar files, grammar1.jj and grammar2.jj, the first grammar is included in the second one.

In the first grammar i have a parser rule like that:

```
void literal(ELNode node):
{
    Token token;
}
{   
	(
		  token = <LONG_LITERAL>
  		| token = <INTEGER_LITERAL>
  		| token = <DOUBLE_LITERAL>
  		| token = <FLOAT_LITERAL>
  		| token = <STRING_LITERAL>
		| token = <BYTES_LITERAL>
    )
    {
    	....
    }
}
```

In the second grammar i want to override this rule and add some more literals:

```
void literal(ELNode node):
{
    Token token;
}
{   
	(
		  token = <DATE_LITERAL>
		| token = <TIME_LITERAL>
		| token = <DATE_TIME_LITERAL>
		| token = <LONG_LITERAL>
  		| token = <INTEGER_LITERAL>
  		| token = <DOUBLE_LITERAL>
  		| token = <FLOAT_LITERAL>
  		| token = <STRING_LITERAL>
		| token = <BYTES_LITERAL>
    )
    {
    	....
    }
}
```

I was expecting only one method literal(node) in the generated parser with the content from the grammar2, but i got the content of grammar1.

So it seems that it is not possible to override parser rules. It could be a nice feature.

**Comment by revusky** [comment]
Salut.

I am a bit confused by what you are saying. What you want to do should definitely be possible. In principle, it simply takes the last production defined, so if you have:

INCLUDE("Included.javacc")

and then later you redefine a grammatical production later in the inluding grammar, it will just use the one that it read last. In fact, JavaCC 21 uses this internally. See: https://github.com/javacc21/javacc21/blob/master/src/main/grammars/JavaCC.javacc#L410

This overrides the grammatical production defined in the included Java.javacc here: https://github.com/javacc21/javacc21/blob/master/src/main/grammars/Java.javacc#L1852

And in the generated JavaCCParser.java file, there is only one Block() method. Otherwise it would not compile!

Alors, je ne sais pas ce qui se passe! En tout cas, ça doit vraiment marcher, me semble-t-il...

À propos, comment tu as entendu parler de ce projet? Je me demande parce que je trouve que je communique avec beaucoup de français, un nombre pas en proportion avec ce que je m'attendrais!

**Comment by timbault** [comment]
Hi,

thank you very much for your examples, it helped me understand something I hadn't realized: the position of statement INCLUDE("grammar.jj") in the second grammar is very important and has an impact on the generated parser! My INCLUDE was located at the end of the second grammar, it is why the literal() method was not overriden (it was actually, but not as I expected).

Now it works fine!

Je suis tombé sur Javacc21 en cherchant à rendre modulaire ma grammaire (JavaCC ne le permet pas). La feature INCLUDE est juste indispensable!

Merci encore pour ce projet!

**Comment by timbault** [comment]
Hi,
i reopen this issue since it is not possible anymore to override rules.
I was using JavaCC21 (Build-Date: 2020-05-10 16:36:42) and it was working fine, but i switched to a more recent version (Build-Date: 2021-03-14 13:42:22) and it did not work anymore, i got this error:
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/timbault/tdm-sandbox-2/tdm-mr-sandbox/projects/javacc.examples.include.v2/target/generated-sources/javacc/examples/include/v2/LangParser.java:[357,23] method literal() is already defined in class javacc.examples.include.v2.LangParser
```
Please see attached projects (v1 with older version, v2 with more recent version).
[javacc.examples.include.v1.zip](https://github.com/javacc21/javacc21/files/6466012/javacc.examples.include.v1.zip)
[javacc.examples.include.v2.zip](https://github.com/javacc21/javacc21/files/6466019/javacc.examples.include.v2.zip)

**Comment by revusky** [comment]
Hmm, that is very strange. I don't know how that regressed. I honestly don't know how long that was broken. At least a couple of months apparently. I thought it couldn't be broken since I use the ability to override productions internally. (I'm pretty sure I do!) I have to look into this.

But it is is a very trivial problem actually, so it is already fixed. Just pick up the latest version and try again.

By the way, the line: PARSER_PACKAGE=javacc.examples.include.v2;

should have quotes, as in: PARSER_PACKAGE="javacc.examples.include.v2";

Was that working before without quotes? I honestly don't think so, but I can't remember for sure! 

In general, it would be preferable if you tried to use the latest version of the tool. I even wrote that as a policy here: https://doku.javacc.com/doku.php?id=technical_support that there is only support if you commit to using the latest version, basically. Oh, and you might consider using the newer streamlined syntax in your grammar files. https://doku.javacc.com/doku.php?id=new_syntax_summary 

It is much more pleasing to the eye and, while it is true that this means that your grammars are not backward compatbile with teh legacy tool, once you use any new feature, like INCLUDE (which is not even that new!) then you don't have backward compatibility anway, so.... It's actually on my mental TODO list to create an automatic converter for the newer syntax, but I still haven't done that.

Oh, and if you like INCLUDE, you might like this also! https://javacc.com/2021/02/01/javacc-21-has-a-preprocessor/

**Comment by timbault** [comment]
Thank you very much. Of course i tried with the latest version before opening this issue.
I confirm that the line PARSER_PACKAGE=javacc.examples.include.v2 was accepted with the version i was using (Build-Date: 2021-03-14 13:42:22).
I will try again with the latest version.
Thank you again!

**Comment by revusky** [comment]
> I confirm that the line PARSER_PACKAGE=javacc.examples.include.v2 was accepted with the version i was using (Build-Date: 2021-03-14 13:42:22).

That is quite strange. Regardless, I fixed that now and you should be able to specify the PARSER_PACKAGE setting either quoted or unquoted.
