### ISSUE TITLE
ParseException could provide more information

### ISSUE THREAD

**Issue by timbault** [javacc21/javacc21#27]
Hi,

when the parser encounters an invalid token, it raises a ParseException with this invalid token. This provides the row and column numbers where the error occurred.

But it could also be very useful to provide the last valid read token and the next expected token. These informations are available in the method that throws the ParseException exception:

```
private void handleUnexpectedTokenType(int expectedType,boolean forced,Token oldToken) throws ParseException {
        if (!tolerantParsing) {
            //	    current_token = oldToken;
            throw new ParseException(current_token);
        }
    }
```

**Comment by revusky** [comment]
Hi, thanks for the comment. 

First of all, I notice that you are using a somewhat old version of the code. Like, if you type:

jar tfv javacc.jar 

what dates is it showing on the files? I just checked and the last prebuilt jarfile I put up at https://javacc.com/home/ is dated 10 May. (That's a bit old, but I haven't done much in the last month. But whatever you are using is surely significanty older.)

So, for one thing, your code snippet above is still using integers internally for the Token type, when the current code uses a type-safe Enum. Well, see here: https://github.com/javacc21/javacc21/blob/master/src/main/resources/templates/java/ErrorHandling.java.ftl#L190

That is the template that generates the method in question, handleUnexpectedTokenType, and it is different from the method signature you provide above. So, I have to say (and please don't take it as a reproach or anything like that) but I can only provide technical help based on the assumption that you are using the up-to-date version of the tool. 
 
And, in this case, the latest version of the code already does incorporate your suggestion!

That said, the whole ParseException API (or really, error handling generally) is something that is kind of in flux right now. There has been a major refactoring, not just using Enums, but also, the fact that I got rid of the TokenMgrError class in the legacy JavaCC. What JavaCC21 does is that, if there is a lexical error, it generates a special kind of Token called InvalidToken, and then, since that obviously can't be parsed, that ends up throwing a ParseException, so there is really only one kind of Exception, not two. 

In any case, I say that because I am very interested in feedback regarding all this error handling API, but of course, I have to insist that people commit to using the most current version of the tool.  And, I admit that this could be a little bit inconvenient at times, that on occasion, you'll have to adjust your code to changes. (Most typically, things will keep working with no changes, but...) So, you might now have to adjust some of your code to the fact that the token type is now an Enum, not an int. But I don't think it will be very hard, and the results will be better in the long term.

**Comment by timbault** [comment]
Hi,

sorry i realize i was using a previous version of javacc21 (april 2020).

Thank you very much for your explanations.

Regards
