### ISSUE TITLE
Customization of error messages

### ISSUE THREAD

**Issue by timbault** [javacc21/javacc21#28]
Hi,

with the last version of javacc21 the error messages give more details (especially the expected tokens and the invalid token).
But i would like to format my own error messages and for this i need to access the invalid token and expected tokens stored inside ParseException instance. It could be useful to get access to these data via getter for example.

Thank you.

**Comment by revusky** [comment]
Well, in this case [INJECT](https://doku.javacc.com/doku.php?id=code_injection_in_javacc_21) is your friend!

If there are private implementation details in any generated class that you want to expose with a getter, you can easily add that using INJECT. (This, by the way, is another feature that JavaCC21 has that is very sorely missing in the legacy tool.)

So, you could easily add to your grammar something like:

<pre>
   INJECT(ParseException) :
   {}
   {
     public Token getLastToken() {return this.token;}
     public EnumSet<TokenType> getExpectedTokens() {return expectedTypes;}
    }
</pre>

And those methods will be _injected_ into the generated ParseException class. Or, alternatively, you could just INJECT a method inside the class that displays your own custom error messages. Also, you know, you can redefine any existing method, like you could  INJECT your own version of PrintStackTrace, for example, and it would overwrite the version of that method defined in the template.

I would just add the following caveat, which should be obvious. If you use private implementation details from ParseException (or any other class) then you are vulnerable to any evolution in the future that could change the implementation details you are depending on. Actually, come to think of it, this would be a good reason, assuming that you have some generally useful methods to add to ParseException, to try to get me to add them to the template that generates ParseException and then you wouldn't have the aforementioned problem of forward evolution (possibly) breaking your code. 

In practice, that whole issue will be less and less of a problem over time because things will get more solidified. The thing is that, in this specific case, the code that has to do with error handling, like ParseException is particularly likely to evolve quite a bit over time, so if you put in a code injection, you might discover that an upgrade breaks that, and you have to adjust a bit. Probably not so big a problem really, but that is just a friendly warning, I guess. (You won't be able to say I didn't tell you so!)

**Comment by revusky** [comment]
By the way, in [the latest version](https://javacc.com/download/javacc-full.jar) there is no need for the empty prologue in the INJECT, so if you aren't going to add any imports or implements, say, you can just write:

<PRE>
   INJECT(ParseException) :
   {
       ... custom methods...
   }
</PRE>

Actually, in recent days, I did quite a bit of adjustments to the JavaCC grammar so that constructs are less verbose. For example, you can write Foo instead of Foo() to reference a production typically, and things like this. Well, you'll see when I have it documented!

Oh, in other matters, could you write me an email at revusky(at)gmail? (Tu peux m'écrire en français aussi, comme tu veux.) I wanted to write you an email, but your github profile doesn't have your email on it.
