### ISSUE TITLE
JavaCC -d does not seem to accept relative Files/URLs

### ISSUE THREAD

**Issue by manticore-projects** [javacc21/javacc21#46]
```bash
mkdir -p ../../target/generated-sources/javacc
java -jar javacc.jar -d ../../target/generated-sources/javacc jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
```

throws
```
Exception in thread "main" java.io.FileNotFoundException: Directory ../../target/generated-sources/javacc does not exist
```

**Comment by manticore-projects** [comment]
```java
baseSource = grammarFileDir.resolve(baseSrcDir).normalize();
```
It appears to me, that you resolve the `OutputDirectory` against the absolute `GrammarFile`, instead of the `WorkingDirectory`.
So in my example above, `OutputDirectory` is resolved to `jjtree/net/sf/target/generated-sources/javacc`.

At least to me, this is unusual and I would like to recommend to change that or document it explicitly.

**Comment by manticore-projects** [comment]
There seems to be another confusion: While the Token files land in the defined Output Directory, the Parser files land under the Current Work Directory (and the Output Directory seems to be ignored). Example:

```bash
are@ryzen ~/d/s/J/s/main (WITHValuesListStatement) [1]> java -jar javacc.jar -d /home/are/Documents/src/JSqlParser21/target/generated-sources/javacc jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt

JavaCC 21 Parser Generator (javacc.jar built by are on 2021-05-16)
Go to https://javacc.com for more information.
(type "java -jar javacc.jar" with no arguments for help)


Outputting: /home/are/Documents/src/JSqlParser21/src/main/java/net/sf/jsqlparser/parser/CCJSqlLexer.java
Outputting: /home/are/Documents/src/JSqlParser21/src/main/java/net/sf/jsqlparser/parser/CCJSqlConstants.java
Outputting: /home/are/Documents/src/JSqlParser21/src/main/java/net/sf/jsqlparser/parser/CCJSqlParser.java
Parser generated successfully.
```

**Comment by manticore-projects** [comment]
Fixed by commit 09e6d71724966668dc594a5b0155eda63badb0b7

**Comment by manticore-projects** [comment]
Unfortunately, I still face some challenges with the "Relative to the Grammar File" Output-Directory.
First of all, I am still not convinced the "relative to the Grammar File" instead of "relative to the Current Work Dir" yields in any pragmatic benefit.
Secondly, even with a lot of good-will I could not get it working but have been forced to determine the absolute location of the `Output Directory` myself and to hand that over instead.

I think, a fair and objective illustration of my challenge is the [ANT Build File](https://github.com/manticore-projects/JSqlParser/blob/JavaCC21/build.xml) I wrote for you:
```xml
        <target name="-pre-compile">
		<property name="output-directory" location="./build/generated-sources/javacc"/>
		
		<mkdir dir="${build.generated.sources.dir}/javacc"/>
		<java jar="./ext-lib/javacc.jar" fork="true" >
			<arg value="-d"/>
			<arg value="${output-directory}"/>
			<arg value="./src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt"/>
			<classpath>
				<pathelement path="${javac.processorpath}"/>
			</classpath>
		</java>
	</target>
```

On my first concern: If `${BUILD.DIR}` and `${SRC.DIR}` are split, then `Relative to the Grammar File` will involve many `parent-dir` directives, in my case `../../../../../../../`. That is annoying but can be done.

On my second concern: I could not get `<arg value="../../../../../../../build/generated-sources/javacc"/>` to work. It kept complaining that it could not generate the file/folder (even when I created the folder upfront). The only solution was to resolve to the Absolute Location by myself, which is easy in ANT (lucky me).

I apologize for much Ado about Nothing, somehow I got it working eventually.
At the same time I feel like this can create a lot of confusion for simple minded end-users like me and maybe would jeopardize the broad adoption of JavaCC21.

**Comment by revusky** [comment]
Well, you could be right about this being confusing for people. I guess the reason that it just never seemed like much of an issue to me was that, now that I think of it, when I am personally just mucking about from the command line, I think I just tend to be in the same directory as the grammar file. So, if the grammarfile I'm playing around with is in:

       ~/temp/test/Test.javacc

I just tend to go:

       cd ~/temp/test
       jcc Test.javacc

I have `jcc` aliased to `java -jar ~/projects/javacc/javacc.jar' in my .zshrc file. (I switched a while from using bash to zsh). So I don't even tend to use -d very much, but even if I did, it wouldn't matter because the current working directory and the directory where the grammarfile are tend to be the same -- I mean, just the way I tend to set up little testpad projects.

Of course, just typing things on the command-line, if you want a directory relative to the current directory, you can just write:

      -d $PWD/../../../foo/bar/baz

or something. Of course, if you put the above in a shell script then the principle of least surprise might be (I say "might be", I'm not sure) would be that a relative directory is relative to where the script is! Of course, if that was what you wanted (on *nix systems anyway, it's:

      -d $(dirname $0)/../../foo/bar/baz

Something like that. In a .bat file on Windows, it's something else, like `-d %cd% ...` for the current directory. and `-d %~dp0%` or something like that. (I just typed those last two from memory!) 

Back in the FreeCC days (circa 2008) I actually wrote an ANT task. You can see that [here](https://github.com/revusky/freecc/blob/master/src/java/freecc/FreeCCAntTask.java) but then eventually axed it when I picked up this work again (early 2020) because I didn't think it did that much and didn't want to have the ant.jar as a build dependency. Also, I was thinking I was going to dump ant in favor something more "modern" which I still haven't got round to doing.

Well, all I can really say is that I am reluctant to spend much mental energy on this sort of thing. I have the nagging feeling that anything one does just tends to be imperfect. As long as it is made perfectly clear that a relative directory is relative to the grammarfile location, then I really think it should be okay.

Oh, here is a thought from out in left field. I had been wondering whether this [jbang](https://dzone.com/articles/jbang-the-power-of-shell-scripting-for-java) thing could be a good option. I'm anticipating having some other command-line utilities, like a lint and stuff and maybe something like jbang could be a good way of consolidating all these various annoying issues. (Not that I know for sure either. I've never used the thing...)

**Comment by manticore-projects** [comment]
On Fri, 2021-05-21 at 11:16 -0700, Jonathan Revusky wrote:
> Back in the FreeCC days (circa 2008) I actually wrote an ANT task.
> You can see that here but then eventually axed it when I picked up
> this work again (early 2020) because I didn't think it did that much
> and didn't want to have the ant.jar as a build dependency. Also, I
> was thinking I was going to dump ant in favor something more "modern"
> which I still haven't got round to doing.
I have to port it to Maven eventually in order to apease the JSQLParser
project.
Personally I do not like Maven much for various reasons. But calling
JAVACC21 is easy enough.
> Well, all I can really say is that I am reluctant to spend much
> mental energy on this sort of thing. 
Agreed.

> As long as it is made perfectly clear that a relative directory is
> relative to the grammarfile location, then I really think it should
> be okay.
Agreed. But it has to work and right now I feel like it is NOT working
as expected.
Please have a closer look at the ANT task again. I could only get it
working with the ABSOLUTE position, but not with the RELATIVE to the
Grammer File one.

> Oh, here is a thought from out in left field. I had been wondering
> whether this jbang thing could be a good option. I'm anticipating
> having some other command-line utilities, like a lint and stuff and
> maybe something like jbang could be a good way of consolidating all
> these various annoying issues. (Not that I know for sure either. I've
> never used the thing.
I have checked it out and did not see the immediate benefit.

Personally I do use Apache Commons CLI for parsing the command line
options and I like it. But you have only 1 or 2 options and our issue
is not about the option itself, but about the functionality behind.
RELATIVE does not work :)

Cheers

**Comment by revusky** [comment]
I'm closing this because it surely is not a real problem. If somebody can't figure out what it means that the BASE_SRC_DIR is relative to the location of the grammar file, then they should get a gun and shoot themselves to remove themselves from the gene pool. Well, I don't really literally mean that, of course, but the real problem is that there is no unambiguously better solution than this and it's such nth order trivia that it's not worth talking about much.
