### ISSUE TITLE
The Method generateParseException() is missing, how to replace it?

### ISSUE THREAD

**Issue by manticore-projects** [javacc21/javacc21#49]
To me it looks like Legacy JavaCC will provide a method `generateParseException()`.
This does not seem to be the case for JavaCC21. What would be the correct replacement please?

Thank you already and best regards
Andreas

**Comment by revusky** [comment]
Generally speaking, you should use the [FAIL statement](https://javacc.com/2020/07/28/new-feature-fail-statement/) -- at least from within a grammar.

Actually, the above-linked article is well worth reading, since it explains that this is actually something broken in legacy JavaCC, the problem being that throwing a ParseException from within a Java code action is treated as a lookahead success because all Java code is treated as a "success".

If you absolutely have to do it from within Java code, probably it is preferable to use the fail(String message) method. You can construct and throw a ParseException instance yourself, but there is some possibility that there will be API drift in the future.

At the moment, I have to admit that there is not 100% clarity on what methods the user should use in various cases (and which ones they should avoid using) but that has always been the case with JavaCC. In retrospect, it is not 100% clear to me that the user is supposed to be calling generateParseException() or maybe they are, I'm not really sure... I think that method exists, as opposed to just newing a ParseException because it throws in some extra information about location and what tokens were expected at this juncture. But you should get roughly the same thing just using FAIL or fail(...)

**Comment by manticore-projects** [comment]
Jonathan,

how do FAIL and "FAULT_TOLERANT=true" work together please.

Example:
```sql
select * from mytable; select * from;select * from mytable2
```

With the previous implementation, we achieved 3 things:
1) the Parser parsed it without throwing an Exception
2) we received a list of 3 Statements (2 good statements and one NULL)
3) we got `parser.getParseErrors()` which gave us information about the erroneous 2nd statement

With the new JavaCC21 Grammer, I can achieve:
1) the Parser parsed it without throwing an Exception (which is cool)
2) we received a list of 3 Statements (2 good statements and one NULL)

but I do not know how to catch the Error Information, because  `parser.getParseErrors()` has no elements.
I tried to experiment with `FAIL` and it fails correctly when `FAULT_TOLERANT=false`. But it does not seem to record the errors when `FAULT_TOLERANT=true`.

My production looks like that (please pay attention to the Exclamation Mark '!' at the end.

```sql
Statement SingleStatement() :
{ 
    Statement stm = null;
    List<WithItem> with = null;
}
{
        (
            (
                [ with=WithList() {  } ]
                (
                    stm = Select( with )
                    |
                    stm = Insert( with )
                    |
                    stm = Update( with )
                    |
                    stm = Delete( with )
                    |
                    stm = Merge( with)
                )
            )
        |
        stm = Upsert()
        |
        ...
        |
        stm = Grant()
        |
        FAIL "No Single Statement found" { parseErrors.add(new ParseException("No Single Statement found!"));}
        )!
	{ return stm; }
}
```

**Comment by manticore-projects** [comment]
Bumping this as it seems to got buried.

**Comment by revusky** [comment]
Hitting a FAIL statement when parsing is effectively the same as throwing a ParseException -- or the same as the parsing machinery throwing the exception, typically when it encounters unexpected input. So, if you hit a FAIL statement in fault-tolerant mode, it just invokes the same recovery machinery that it would otherwise. In non-fault-tolerant mode, the exception just bubbles up and if fault-tolerant mode, it is caught and some error recovery heuristics are applied. If you really really wanted the exception to bubble up in a specific case, you would need to turn off the fault-tolerant mode.

      setFaultTolerantParsing(false);

The key difference between `FAIL` and explicitly throwing an exception is if you are in a LOOKAHEAD, because hitting a FAIL is taken to be a failure while throwing an exception in your Java code is taken to be a "success" of the lookahead. This is one of the various things that have been broken forever in legacy JavaCC that would actually be extremely easy to fix.

**Comment by revusky** [comment]
I'm pretty sure this is answered adequately now.
