### ISSUE TITLE
Restructure the project with maven, gradle ?

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#5]
It seems that there are some bat files to build the project. IMHO project should use maven or gradle project to do that.

**Comment by revusky** [comment]
Well, the .bat files I had a long time ago before there even was Gradle. I figured I'd just keep them working for now. Actually, you can run the tool just with: 

java -jar javacc.jar

Actually, the launch scripts in the bin directory are a little more fancy, since they use the .class files (and code generating templates) in the ../build directory if they are there. If they are not present, they fall back on using the bootstrap javacc.jar file in the bin directory. I call it the "bootstrap" jarfile because, since JavaCC is used to build itself, there needs to be a javacc.jar file already present. So, the launch scripts try to use your build (that is in the build directory) but if that is not there, they fall back on the bootstrap jar in the bin directory. And that would be the setup one tends to use in development. To be absolutely sure something works, you would want to test it using the latest version you built and then sometimes you also want to test using the "bootstrap" jarfile. So you delete the build directory and retest.

But anyway, yeah, probably gradle and/or maven are a good idea, mostly because they are such standard things now, but I have to say it is not a very high priority for me because I am just so much in the actual code and I don't see that there is any problem that needs fixing urgently with any of this. Actually, if you just checkout the code and run ant from the top-level directory, it should just work. On any platform, Windows, Mac, Linux... I always do my best to try to make it very easy for people to get started.

To tell the truth, it almost seems like a stylistic thing. Using ant is a bit passé, but not a big problem either, something like wearing clothes that are out of fashion. You might look a little silly but functionally, it is pretty okay!

**Comment by angelozerr** [comment]
Fixed with https://github.com/javacc21/javacc21/commit/297ea2a5f6303006131c1986241bc68496bbc34b

Maven is used now. We have travis too https://travis-ci.org/github/javacc21/javacc21
