### ISSUE TITLE
The generated Parser kills the JVM! 

### ISSUE THREAD

**Issue by manticore-projects** [javacc21/javacc21#51]
Crazy stuff, I actually do not even know how to write this bug report:

1) I have ported the SQL Grammar to JavaCC 21 and am able to run the most of the SQL Parser tests already

2) However, there is one test suite, which literally kills the JVM. It consumes all 16 CPU cores, takes out a big chunk of the memory (but never exhausts the memory) and runs forever. Soft-kill won't help. I have to kill hard per `pkill -9 java`. It's not a JVM issue, I have tested with various VMs between 8 and 11 from various Vendors (Oracle, Adopt JDK, Jetbrains).

3) The test itself looks innocent to me:
```sql
CREATE FUNCTION foo RETURN 5; END;
```

Something in this Syntax makes the parser go helter skelter.
I also could not attach a profiler, because the JVM goes belly up. What information should I provide to hunt this down?

**Comment by revusky** [comment]
Well, I just looked at this and it seems to be roughly the same problem you had elsewhere. The problem is in the captureRest() method and basically, again, the `getNextToken()` method, like `nextTokenType()` does not actually advance the token position. You would need to replace:

      tok = getNextToken();

with:

      tok = nextToken(tok);

Otherwise, it's just always returning the same token on each iteration of the loop and adding it to the LinkedList, and eventually the whole thing blows up, I suppose. I have to admit that the `getNextToken` API is somewhat anti-intuitive. Well, the wau tp conceptualize it is that the methods that take no args are just returning the next token (or token type) relative to your current position (either in parsing, `lastConsumedToken` or in a lookahead, `currentLookaheadToken`. It returns the token immediately after that. The method you need is actually `nextToken(tok)` to get the token that immediately follows token passed in as a parameter. So you'd be continually getting the next token *relative* to the last one you grabbed. And then the code should work as intended, as opposed to just going on forever.

Well, again, these are methods that probably one should not even be using at the application programming level. I say *probably* because I have to be honest and admit that this whole thing is not defined so well. But it is pretty clear that if it is error recovery you want, you should be trying to use the fault-tolerant machinery that was put in place in the last few months. You'll eventually get far more satisfactory results, I daresay!

**Comment by manticore-projects** [comment]
Thank you very much, that was the correct hint and I would not have found that in 100 years because the JVM goes belly up fast when it happens, making it very difficult to debug.

I have fixed it and ensured, that `captureRest()` produces the exact same list of token images as before with Legacy JavaCC.

But now I face another problem: How to consume these tokens? After calling `captureRest()` the Parser still assumes, we are at the last token before `captureRest()` and so the parse fails.

Example:
```sql
CREATE FUNCTION foo RETURN 5; END;
```

```java
CreateFunctionalStatement CreateFunctionStatement():
{
  CreateFunctionalStatement type = null;
  List<String> tokens = new LinkedList<String>();
  String statementType = null;
  boolean orReplace = false;
}
{
  <K_CREATE> [<K_OR> <K_REPLACE> { orReplace = true; } ]
  (
   <K_FUNCTION> { statementType = "FUNCTION"; }
   |
   <K_PROCEDURE> { statementType = "PROCEDURE"; }
  ) 
  { tokens=captureRest() };

  // we are still at "foo" of type S_IDENTIFIER
  // but we expect to be at "EOF"
  // how to skip to then end here and ignore any further tokens?

  {
    if(statementType.equals("FUNCTION")) {
      type = new CreateFunction(orReplace, tokens);
    }
    if(statementType.equals("PROCEDURE")) {
      type = new CreateProcedure(orReplace, tokens);
    }

    return type;
  }
}

INJECT PARSER_CLASS : {
    List<String> captureRest() {
      List<String> tokens = new LinkedList<String>();
      Token tok =  getNextToken();
      
      while(tok.getType()!=TokenType.EOF) {
        tokens.add(tok.getImage());
        tok = nextToken(tok);
      }

      return tokens;
    }
}
```

In the same above, the "Production" parses up to `foo` and then calls `captureRest()`, which will return `foo RETURN 5; END;`. Now we should be at `EOF` but unfortunately we are still at `foo`.

How to tell the "Production" to simple move to the end or to ignore any tokens from here or to simply just break? 

The Legacy Grammar looked like that
```java
  <K_CREATE> [<K_OR> <K_REPLACE> { orReplace = true; } ]
  (
   <K_FUNCTION> { statementType = "FUNCTION"; }
   |
   <K_PROCEDURE> { statementType = "PROCEDURE"; }
  )
  tokens=captureRest()
```

I believe, the missing Curly Brackets "{}" consumed the tokens, but I failed to make that work with JavaCC21.

Thank you again, it is an amazing journey!

**Comment by manticore-projects** [comment]
I did it! Reading through 5MB generated Parser Java Code, I figured that I have to call `consumeToken()` to move ahead.

```java
//JAVACODE
INJECT PARSER_CLASS: {
    List<String> captureRest() {
      List<String> tokens = new LinkedList<String>();
      Token tok =  getNextToken();
      
      while(tok.getType()!=TokenType.EOF) {
        tokens.add(tok.getImage());
        try {
          consumeToken(tok.getType());
        } catch (ParseException ex) {
        }
        tok = nextToken(tok);
      }

      return tokens;
    }
}
```

It seems to be like a dirty hack though and I would be still interested to learn the clean way of doing so.
Please note: There is no practical way to define all the allowed Tokens between `FUNCTION foo` and `END;`.

**Comment by revusky** [comment]
Well, the current situation wrt documentation of this sort of thing is not good right now. And, unfortunately, I suppose it's not going to get that much better in the near term because, actually, I'd be a bit reluctant at this stage to commit myself to these things being stable over the coming months.

Now, generally speaking, the application programmer should not really have to be using this stuff anyway. At least, not in *normal* or *typical* usage. (Though I grant that does beg the question a bit of what is "normal" or "typical"....) Well, I think that what some of this highlights is that some of this still is a bit raw. Well, ideally, in a more mature state of things, there should generally be higher level constructs that the application programmer uses. And then it can be easier to commit to those things being stable. For example, it is easier for me to commit to `FAIL ...` continuing to work as opposed to `throw new ParseException(....)` because it is easy to imagine that the args to the constructor of ParseException could change, but we can still keep the higher-level FAIL construct working even if the ParseException API changed behind the scenes.

So, once you start using methods like `consumeToken` or fields like `lastConsumedToken` in your code, it's sort of a similar situation. I'm not saying absolutely don't do it because if there is no choice at the moment.... However, obviously, in the case where there is a higher level construct available like `FAIL` as opposed to directly instantiating and throwing a ParseException....

Well, the key thing to understand in this case is that the generated parser is maintaining a "cursor" or "bookmark" if you will, of where it is in the parse, which is `lastConsumedToken`. So, if what you really want to do is to ignore the next n tokens, say, you need to set the `lastConsumedToken` field to the last of those n tokens so that the next token fed to the parsing machinery is the one right after that one. Also it seems that you have to unset the nextTokenType field (i.e. set it to null) because that is cached for efficiency purposes.

But note that what this is about is getting the extremely primitive error recovery machinery from JSQLParser working. With the (still relatively new) fault-tolerant machinery in JavaCC21, you really shouldn't need this. But, okay, I understand the situation, so I guess the main point here is that you are running into these problems because you're failing to set `lastConsumedToken` and then wondering why the parsing machinery is not reset to the more advanced position, you see....

**Comment by manticore-projects** [comment]
Closing this for consolidation.
