### ISSUE TITLE
Potential null pointer access

### ISSUE THREAD

**Issue by MarcMazas** [javacc21/javacc21#53]
Example: FELParser.java, line 971: AdditiveExpression7.setDirty(true); shows a potential null pointer exception,
despite it is within a if (buildTree) { ... }, as AdditiveExpression7 = new AdditiveExpression(); (line 897)

This can happen as buildTree is not final and can be changed through setBuildTree(...).

Does JavaCC21 manage using this last method to turn off/on building the tree within a program ? May be it should be a one call only method.

**Comment by revusky** [comment]
Yes, you're right. There is some possibility that the `buildTree` variable changed, since `setBuildTree` could be called by a code action in the middle of a parse. That said, it is probably a very rare usage pattern. Most typically, somebody would call `setBuildTree` immediately after instantiating a parser. You know, something like:

        MyParser parser = new Parser(....);
        parser.setBuildTree(false);
        parser.Root();

To call `setBuildTree` in the middle of parsing this way would not be a common usage pattern at all! That said, somebody could do it and, the way the code was written, it would either cause an NPE or if not, would mess up all the NodeScope nesting logic. The node scope would possibly get opened but never closed.

So it is an issue and since it is so trivial to fix... 

One thing about this, I would say is that if you make any more bug reports (which I would be quite happy if you did), if the bug is in *generated* code, you should try (if possible...) to report it relative to the template that generated the code, not the code that was generated. So, for example, the problem is (or was, more precisely) [here](https://github.com/javacc21/javacc21/blob/master/src/main/resources/templates/java/ParserProductions.java.ftl#L176).

At least, I'm pretty sure that fixes the issue. I can't resist asking the following question, though knowing you, you'll probably avoid it. (Though you can surprise me!)

What would be the expected time for Sreeni and Francis André and the gang over there to fix a bug of this nature? You can answer the question in any time unit you want: days, weeks, months, years... 

*Decades???*

*Or hours, minutes, seconds, microseconds...* After all, I can convert the units. Just curious what your estimate would be...

**Comment by MarcMazas** [comment]
<So it is an issue and since it is so trivial to fix.../>
Well, I assume you know what you're doing by fixing it like this.
I would probably restrained myself conditioning only the offending line.

**Comment by MarcMazas** [comment]
<What would be the expected time for Sreeni and Francis André and the gang over there to fix a bug of this nature/>
Well, I would have fixed it for you and for JavaCC if I found the way to make my push commits work (git-receive-pack error) :)
And in fact the corresponding feature does not exist in JavaCC

**Comment by MarcMazas** [comment]
>  Well, I assume you know what you're doing by fixing it like this. I would probably restrained myself conditioning only the offending line.

Or may be I would have removed the setter and made the variable final, preventing the user from playing with unintended feature.

**Comment by MarcMazas** [comment]
About the PR merge delay: see Javacc #202 & #203 compared to JavaCC21 #57?
Looks like Euro Cup has started... FR-1/SP-0
