### ISSUE TITLE
Hard coded project name

### ISSUE THREAD

**Issue by MarcMazas** [javacc21/javacc21#54]
Parser-gen.launch refers to ${workspace_loc:/javacc}, which is invalid if the project is not named javacc (like javacc21, in random).
Would simplify version control if it was variabilized.

**Comment by revusky** [comment]
Well, Parser-gen.launch is a file that Eclipse generates, and yes, the name of the project on my system is simply "javacc". I haven't used Eclipse for a while but I cannot recall any option to make the project name a variable. But I very much doubt that there is any real problem here anyway. Your "issue" seems to be based on the idea that there is another project called "javacc" in the same workspace. Well, look... there is only one JavaCC project that is being developed in any serious, meaningful way and you could avoid a lot of wasted time by finally understanding that. There is only one javacc project that a person with a minimum of good taste would want to get involved in from a development point of view.

I earlier asked you the question of whether you were raising all these various issues because you really wanted to learn the code and work on it, or whether you were trying to get Eclipse to emit no warnings as a kind of *empty formalism*. If it is the latter, then it's your time, okay, but I don't think you should be making any demands on my time if the whole thing is really just some sort of sterile hobbyhorse.
