### ISSUE TITLE
no build for example/csharp

### ISSUE THREAD

**Issue by MarcMazas** [javacc21/javacc21#56]
.classpath contains <classpathentry kind="src" path="examples/csharp"/>, so examples/csharp is a source folder, but build.xml does not contain any target to build it.
Result is that Eclipse Automatic Build shows errors for this grammar.

**Comment by revusky** [comment]
Well, the truth of the matter is that the csharp example is not working. (Yet.) I guess I was mucking with it and VSCode added it to the .classpath. (I have no recollection of ever manually editing the .classpath file.) I guess, at some point, I decided to check in files like that because I figured it gives people a leg-up in terms of getting their own work environment going, but to tell the truth, I don't feel like I've undertaken a serious commitment to have everything working in an IDE with no fuss at all. Something like `ant clean jar test` should work for everybody with zero configuration. I feel committed to that, but I guess I take it as a given that people might have to tweak some things to get things working smoothly in` an IDE like Eclipse or IntelliJ.

It occurs to me that it might be better not to check in those files at all and just have samples available. Like _classpath.sample and even add .classpath (and other similar things) to .gitignore.

Now that I have the lexical generation completely rewritten, I think that targets for other languages, like C# should not be far off. This is because I can port the template to generate C# and just the lexical generation part on its own is  already useful. I have that down to two templates:

https://github.com/javacc21/javacc21/blob/master/src/main/resources/templates/java/LexerCode.java.ftl

and:

https://github.com/javacc21/javacc21/blob/master/src/main/resources/templates/java/NfaCode.java.ftl

In principle, if you translate those two templates to generate C# (or any other language) you have the lexer generation working for that language. It is looking like a pretty manageable task. Well, also you'd need Token.java.ftl and FileLIneMap.java.ftl (or even just simplified versions). With those 4 templates translated, you'd have the full Lexer generation going for C#. To get the full parser/lexer combo working for C#, there is the need for a parser for C#, analogous to the Java parser in examples/java. But, as I say above, that is not working yet.

Some moons ago, you asked me if I "master" (*maitrise*) all that BitVector gibberish. Well, the answer then was that I didn't fully understand it. But the answer now is that I definitely gained the upper hand over all that, since it is all gone, completely rewritten.

All that stuff is rewritten in less than 1000 lines. It's about 300 lines of FreeMarker and 500 lines of Java. It's written pretty straightforwardly now. It's nothing to be afraid of. It should only be a moderate intellectual investment to get one's head around that.

Oh, you also asked me whether I understood this stuff about generating "phase 2" and "phase 3" lookahead methods. Well, phase 3 is really nested lookahead, which was always broken in various ways in legacy JavaCC. That is all rewritten and works correctly. well, there could still be a corner case bug here and there, but surely people like you will run into those cases and report them...

**Comment by MarcMazas** [comment]
<It occurs to me that it might be better not to check in those files at all and just have samples available. Like _classpath.sample and even add .classpath (and other similar things) to .gitignore./> why don't just remove them from the build path, and add a small readme.md explaining all your reasons aabove?

**Comment by revusky** [comment]
> why don't just remove them from the build path, and add a small readme.md explaining all your reasons above?

Why don't I? Well, it takes time and I have to allocate my time sensibly.

The first-best solution to this whole thing would be to actually get the Csharp example working. But that will take some time. Maybe you'd like to write a Csharp grammar. Then we wouldn't have this problem.

**Comment by revusky** [comment]
Today I did some major simplification of all this stuff. I got rid of all the half-baked mavenization and just went back to pure ant.
