### ISSUE TITLE
Why the unncessary condition?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#71]
https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/LookaheadRoutines.java.ftl#L384

No doubt the compiler will optimize accordingly, but why is there an `if (true)` condition here?

**Comment by revusky** [comment]
Oh, that is one of these quirky things you have in code generation in Java. For example, suppose that under some conditions, you want to just jump out of some generated method, so you might end up generating something like:

         void some Method() {
                blah blah...
                return;
                 blah blah blah
          }

This won't compile because the blah blah blah is *unreachable code*. BUT... if you generate instead:

         void someMethod() {
                   blah blah...
                   if (true) {
                       return;
                    }
                    blah blah blah
          }

then the code compiles! Of course the blah blah blah is just as unreachable as it was before, but the compiler doesn't analyze that. Actually, I was a bit leery of relying on this trick. (BTW, the legacy tool relies extensively on this trick in its code generation.) I was wary of this for a good while because I thought that, at some point, the compiler would get "smarter" and then identify the continuation code as unreachable and then suddenly, it wouldn't compile, but actually, it's in the JDK spec, that this trick will continue to work!

The relevant biblical passage is here: https://docs.oracle.com/javase/specs/jls/se16/html/jls-14.html#jls-14.22

If you can get through the prose, the upshot of the matter is that in the second code snippet above, the blah blah blah is NOT considered unreachable code in terms of refusing to compile it. OTOH, the compiler could well realize that it doesn't need to compile that code because it is in fact unreachable, but it is not unreachable from the point of view of being illegal and thus, refusing to compile it. And this actually is, to some extent, a convenience for tools that generate code.

Here is another one that you will surely come across at some point: https://github.com/javacc21/javacc21/blob/master/src/ftl/java/ParserProductions.java.ftl#L148

You might ask why we have `if (false) throw new ParseException("never happens!");` and the reason is kind of similar. The block is wrapped in a try-catch, but if that particular generated block never does throw that kind of checked exception, the compiler complains saying that the block never throws ParseException, but if you add that `if (false)...` there, then it doesn't complain any more, because the block does potentially (according to its analysis) throw ParseException, except that it never does! And, again, probably the compiler is "aware" on some level that the whole thing is for nothing and most likely does not even generate the code for the dead code in this case! But it compiles!

Well, all of this is just sort of quirky heuristic knowledge that you need to generate code in Java. So I hope that answers your question!

**Comment by vsajip** [comment]
OK, I thought it might be something like that - thanks for the spec pointer!

On the `if (false)` thing, I get that. In Python there is an analogous situation in that a block isn't allowed to be empty (since it's defined by indentation), so there is a no-op statement `pass` that you stick in a block if there's a possibility that it will be otherwise empty because of how code is generated. Hence:
```python
try:
    pass
    # other code generated here, but might be absent
except Exception as e:
    pass
    # other code generated here, but might be absent
finally:
    pass
    # other code generated here, but might be absent
```
