### ISSUE TITLE
Will state.index be different from state_index in the #list? If not, I could generate slightly clearer code for Python here 

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#72]
https://github.com/javacc21/javacc21/blob/924cd19c15cc64abae8330dfdb37cac0c739911c/src/ftl/java/NfaData.java.ftl#L126-L128

**Comment by revusky** [comment]
Yeah, it seems like state.index and state_index are always the same in that loop. I'm pretty sure that, in an earlier version of the code that wasn't the case, because at some point, I decided to sort the states by index when exposing them to the template. Here:  https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/core/LexicalStateData.java#L75-L79

But, to tell the truth, I think I actually did that for aesthetic reasons more than anything else. But I guess it is the case that state.index and state_index are always going to be the same there.

**Comment by vsajip** [comment]
OK, thanks for the info.
