### ISSUE TITLE
Current AST from included Java grammar not ideal for translating - any remedies?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#73]
I'm looking at how best to translate various snippets that are found in grammars. In some cases, the AST that's currently built is sub-optimal for translation. For example, in the Java grammar here:
https://github.com/javacc21/javacc21/blob/211ee5b38a37054fd9db3285518179d18c777432/examples/java/Java.javacc#L626-L629

Some (though not all) translation difficulties are caused by the Python way of indicating container membership: Java's A.contains(B) should become (B in A) in Python. However, the current AST makes the detecting the presence of the `contains()` method call harder than it should be. For example, the source expression

```java
permissibleModifiers.contains(getToken(1).getType())
```

the ideal AST would be something like
```
                                     +------+
                                     | Call |
            +------------------------+--+---+--------------+
            |                           |                  |
            |                           |                  |
            |                           |                  |
+-----------v----------+         +------v------+       +---v--+
|    Call target       |         | Method name |       | Args |
| permissibleModifiers |         |   contains  |       | (one)|
+----------------------+         +-------------+       +---+--+
                                                           |
                                                       +---v--+
                                                       | Call |
                                     +-----------------+---+--+----------------+
                                     |                     |                   |
                              +------v------+       +------v------+        +---v--+
                              | Call target |       | Method name |        | Args |
                              |    Call     |       |   getType   |        |(none)|
          +-------------------+------+------+-----+ +-------------+        +------+
          |                          |            |
+---------v----------+        +------v------+  +--v---+
|     Call target    |        | Method name |  | Args |
|null (implying this)|        |  getToken   |  | (one)|
+--------------------+        +-------------+  +--+---+
                                                  |
                                                  |
                                             +----v-----+
                                             |Expression|
                                             |    1     |
                                             +----------+
```
Whereas what we have currently is

```
                                    +-------------+
                                    | PrimaryExpr |
              +---------------------+------+------+
              |                            |
              |                            |
              |                            |
+-------------v---------------+         +--v--+
|           Name              |         |Args |
|permissibleModifiers.contains|         |(one)|
+-----------------------------+         +--+--+
                                           |
                                    +------v------+
                                    | PrimaryExpr |
           +-----------+---------+--+-------+-----+--------+
           |           |         |          |              |
           |           |         |          |              |
      +----v----+   +--v--+  +---v---+  +---v-------+  +---v---+
      |  Name   |   |Args |  | Delim |  | Identifier|  |  Args |
      |getToken |   |(one)|  |   .   |  |  getType  |  | (none)|
      +---------+   +--+--+  +-------+  +-----------+  +-------+
                       |
                       |
                     +-v-+
                     | 1 |
                     +---+
```

Do you think it is better to make changes to the grammar to get closer to a desired AST? If not, what do you think would be a good way to transform the AST currently generated? By which I mean, do you know any good tools/techniques which would make short work of it?

**Comment by revusky** [comment]
> I'm looking at how best to translate various snippets that are found in grammars. In some cases, the AST that's currently built is sub-optimal for translation. For example, in the Java grammar here:
> https://github.com/javacc21/javacc21/blob/211ee5b38a37054fd9db3285518179d18c777432/examples/java/Java.javacc#L626-L629

Yeah... Well, let's see... I've been aware, i.e. it's been a nagging issue somewhere in the back of my mind, that this part of the Java grammar is not very elegant or intuitive. I mean, the tree that is built is a parse tree that emerges from applying the Java language spec in a rather bloody minded way. BTW, the appropriate biblical passage is [around here](https://docs.oracle.com/javase/specs/jls/se16/html/jls-15.html#jls-15.8). In fact, funny enough, you can see that the authors of that section admit that the whole thing is structured in a rather unintuitive way. You now, this part: *This part of the grammar of the Java programming language is unusual, in two ways....*

One casual observation one could make about this is that it does not really correspond to how a working Java programmer thinks about these constructs. I mean, even just the term "primary expression", if I had never got so deeply into this language parsing field, I would not even known what that term meant. OTOH, everybody would know what a "method invocation" or "array allocation" is, right? So, [this code injection](https://github.com/javacc21/javacc21/blob/211ee5b38a37054fd9db3285518179d18c777432/examples/java/Java.javacc#L655-L711) is definitely rather inelegant and unnatural. It would be much more natural to have a node type that is a MethodInvocation or a ConstructorInvocation, and so on. Instead, we have a node type that is PrimaryExpression and then I have these methods inserted in there to ask whether the thing is a method invocation or whatever.

So, for example, you see here: https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/java/JavaCodeUtils.java#L88

What I do there is that I want to get all the method invocations, but I do it by asking for all the PrimaryExpression objects such that the ::isMethodCall returns true. On the one hand, it's nice that things like this can be expressed pretty succinctly in Java nowadays, but it would be much nicer if that code read more like:

      for (MethodInvocation mi : jcu.descendants(MethodInvocation.class)) {
                       ....
      }

Well, all that said, one point to make about this is that all the information is there, so in principle, it is possible to munge this unintuitive tree into something more intuitive that you can work with more easily. BUT... if we could find a way to generate a more natural tree structure directly, that would surely be better. Also, generally speaking, the ability to manipulate Java code that is already inside of JavaCC21 is fairly attractive, but I haven't really documented it hardly at all. I may have already told you that I am intending to write an article for Oracle Java Developer Journal about this topic (though after the first article appears, which is already written and submitted and should appear soon) but it could well be worthwhile to really revisit this sort of thing first. So I'm quite happy that you're bringing this up.

> 
> Some (though not all) translation difficulties are caused by the Python way of indicating container membership: Java's A.contains(B) should become (B in A) in Python. However, the current AST makes the detecting the presence of the `contains()` method call harder than it should be. For example, the source expression

Well, again, in principle, one can rewrite the tree in a more amenable form, since all the information is there. But it would be better if the thing generated a tree much closer to what you want in the first place. 

> 
> Do you think it is better to make changes to the grammar to get closer to a desired AST?

In a word, yes, I think so. Though, to be clear, I don't think there is any need to change the syntactic grammar rules really, but more a question of tweaking the tree-building annotations. This might also be a point to use the close node scope hook mechanism to manipulate the tree more to the form that you really want. There is an example of using that hook here: https://javacc.com/2020/03/14/a-fun-example-of-code-injection-at-work/

> If not, what do you think would be a good way to transform the AST currently generated? 

Well, I think that we should try to generate an AST directly that is more intuitive and natural. But if we did just take the current AST as given, then it would be a question of just using a Node.Visitor and walking over the tree and generating the tree (or subtree) that we actually want. I have a base Node.Visitor class that I use internally that makes use of reflection and is (IMHO) far more elegant than the mechanism that JJTree uses. Actually, I think that whole JJTree thing may have been designed before Java had reflection! What Node.Visitor does is it just checks if the visitor object has a handler of the given name and invokes it, or if not, by default, recurses over the child nodes. See: https://github.com/javacc21/javacc21/blob/master/src/ftl/java/Node.java.ftl#L773

That is used here: https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/core/NfaBuilder.java

That is the code that builds all the NFA states! It's just  tree visitor and it gets unleashed on the root of the subtree that represents the given regular expression. Well, I'll close this note here. Maybe I'm starting to show off now, which is not a good thing... Though, I think the various places I point to do probably fill in some info.

>By which I mean, do you know any good tools/techniques which would make short work of it?

**Comment by vsajip** [comment]
> Well, I think that we should try to generate an AST directly that is more intuitive and natural.

I agree. But I will leave those sorts of changes to the Java grammar to you, as you'll have a better understanding of any knock-on effects.

> But if we did just take the current AST as given, then it would be a question of just using a Node.Visitor and walking over the tree and generating the tree (or subtree) that we actually want

Yes, but that is fiddly and error-prone (I'm trying it now) and there's no strong reason for the AST to remain as it is (apart from the fact that JavaCC internals will need to change to suit). But I've just thought of something else - which I will post as a separate issue.

**Comment by revusky** [comment]
> > Well, I think that we should try to generate an AST directly that is more intuitive and natural.
> 
> I agree. But I will leave those sorts of changes to the Java grammar to you, as you'll have a better understanding of any knock-on effects.

Having slept on this and looked at it a bit more, it seems that it is not so easy. If you build a parse tree in a bloody minded way based (more or less) on the JLS, you end up with something like what we have currently. And that works, except that it generates a tree that is rather unintuitive in spots. You have this "primary expression" construct that doesn't really correspond to how a person thinks. But to rewrite that so that it generates something more intuitive does not look terribly easy and it is uncertain whether it is a good investment of our (my) time at this juncture. There are so many things to do...

But I think this question may relate to a sort of big question that has been puzzling me over the last year at least. And that question is: why are parser generator tools so under-utilized? 

And another related question is why the application space seems so stagnant.

I think that a lot of people who need a parser for a complex language like Java frequently end up coding it by hand. And that is a rather strange situation since YACC came out back in 1975. You'd think that the field would be very mature by now and it would be unthinkable to write a Java (or Python or fill-in-the-blank) parser by hand. But that does not seem to be the case. For example, the Java parser inside of javac is hand-written. And that's just one example...

I think error handling is a real biggy, like even just generating comprehensible error messages. A tool like JavaCC can generate error messages but (unless a lot of care is put into this) they tend not to be very comprehensible to a person. The error messages can be quite correct and logical in terms of how a parser generator "thinks" but that isn't how humans think about the problem. In fact, back in the FreeMarker period, one of my obsessions (I mean, probably 2002-2003 period) was generating good (or as good as possible) error messages. That may actually might be the single biggest reason that (much to my suprise) FreeMarker is still widely used.

Well, that's all just a tangent anyway. It's sort of in the back of my mind to generate a more intuitive AST from Java source in these spots, but it probably is rather typical that the parse tree that such a tool directly generates frequently does not correspond to how a human thinks intuitively about the problem. So, it's in the back of my mind to do something about this (maaaybeee) but I don't think it's a high priority right now.

> 
> > But if we did just take the current AST as given, then it would be a question of just using a Node.Visitor and walking over the tree and generating the tree (or subtree) that we actually want
> 
> Yes, but that is fiddly and error-prone (I'm trying it now)

I think ANTLR has some sort of tree-rewriting notation inside of it. I never really looked at it closely. I don't know whether it's that much better than just coding a visitor -- which, I agree, is not that simple. But with that tree rewriting, I guess you can sort of declare that your final tree is a bit different from the parse tree that the tool tends to generate by default.

In general, I tend to think that best practice of a tool like JavaCC is probably (in typical usage) to generate the bloody-minded KISS parse tree, even if it is unintuitive, and then possibly in a second pass to do whatever manipulations (including possibly rearranging the tree somewhat) prior to your final processing of the information. The final processing of the information inside of JavaCC21 is just to expose all the data structures to the templates and that generates the code.

>and there's no strong reason for the AST to remain as it is (apart from the fact that JavaCC internals will need to change to suit). 

Well, for the moment, being able to generate a parser that builds an intuitive tree, generates intuitive error messages and so on, is kind of a black art. I mean, it's a black art using a tool like JavaCC, but all the more so coding the parser by hand. But that seems like something that is incredibly time-intensive and error-prone! Of course, the other reason for the under-utilization of parser generators is surely that it's just wrapped up in all this sort of jargon and mystique...

I'd like to do something about that. I have no idea why really. What do I care if parsing is wrapped up in all this mystery and jargon? Maybe it provides an easy living for some people, I dunno. I guess if it was between addressing this problem and solving poverty and hunger in the world, I'd go for the latter, but that is totally beyond my ability, so....

>But I've just thought of something else - which I will post as a separate issue.

**Comment by vsajip** [comment]
> it generates a tree that is rather unintuitive in spots. You have this "primary expression" construct that doesn't really correspond to how a person thinks. But to rewrite that so that it generates something more intuitive does not look terribly easy and it is uncertain whether it is a good investment of our (my) time at this juncture. There are so many things to do...

The current tree is very syntax-oriented. It keeps *everything* - including punctuation like parentheses around parameter lists and casts, semicolons and so on - and while I can see that might be useful in some applications, things get in the way when you want to do something like code generation (after all, that's the classic application of compilers). In my past use of JavaCC (the old Sun version), I generally never used JJTree but built my own tree in the actions.

> But I think this question may relate to a sort of big question that has been puzzling me over the last year at least. And that question is: why are parser generator tools so under-utilized?

One reason might be that they don't make things as easy for the developer as they could be. For example, your own recent innovations do make things easier for JavaCC users, but look how long the project has stagnated before you picked it up again recently. There's no money in language development directly, really, so it's the kind of work that has to be done either for love or in pursuit of wider goals (where there is indirect money from corporate sponsorship/investment to further those wider goals - things like TypeScript, Dart, Rust, Swift come to mind). 

> I think that a lot of people who need a parser for a complex language like Java frequently end up coding it by hand. And that is a rather strange situation since YACC came out back in 1975.

Personally, I'll take LL(k) recursive descent over LR(k) tools like YACC for many applications. For example, you often want to be easily be able to choose the production to start with, and LR(k) usually doesn't give you that, or at least it was hard to do with LEX/YACC back in the day when I used them.

> I think error handling is a real biggy

Yes indeed, the state of the game isn't good enough to automatically provide good error messages that are useful to developers. The poster children here are clang and Rust, which have reasonably good error messages (though perhaps not always with C++ arcana).

> Well, that's all just a tangent anyway. It's sort of in the back of my mind to generate a more intuitive AST from Java source [...] but I don't think it's a high priority right now.

Fair enough, but then I think the Python code generation will also take a lower priority since it couldn't progress beyond a certain point without some improvement in the AST. There's also the question of injections (#74).

> In general, I tend to think that best practice of a tool like JavaCC is probably (in typical usage) to generate the bloody-minded KISS parse tree, even if it is unintuitive

I'm not sure I agree, depending on what the parser is used for. If used for transpiling as in our case, the AST definitely needs to be more closely oriented to program language semantics than to syntax. Like the box diagram I posted earlier.

> Well, for the moment, being able to generate a parser that builds an intuitive tree, generates intuitive error messages and so on, is kind of a black art.

One never knows till one tries ...

**Comment by revusky** [comment]
> The current tree is very syntax-oriented. It keeps _everything_ -

Well, yeah, and that's quite deliberate. I just reason that, since the tool cannot read your mind, at least by default, it builds a tree that does not throw away any information. So, actually, strictly speaking, it's a CST (concrete syntax tree) more than an AST. Though, that said, it seems pointless to be a stickler about CST vs. AST terminology. I suppose I'll frequently say AST when we're really talking about a CST, but.... so what...

Now, granted, it's wasteful in terms of memory to store every last comma if you don't need it, but it really just doesn't seem that it matters that much at this stage of history.

> including punctuation like parentheses around parameter lists and casts, semicolons and so on - and while I can see that might be useful in some applications, things get in the way when you want to do something like code generation (after all, that's the classic application of compilers). 

True, but again, in the general case, we don't know what the person is trying to do. So the natural approach from my POV is to err on the side of including too much information in the tree, like basically everything! In any case, the generated parsers are quite fast. On typical current hardware, one can parse the entire JDK 16 source code (what is in src.zip, 14,418 files) with full tree building in about 40 seconds. 

>In my past use of JavaCC (the old Sun version), I generally never used JJTree but built my own tree in the actions.

Well, that's also what FreeMarker does. (When I finally get round to rewriting the core of FreeMarker, it will use the automatic tree-building and I'm confident the code will be much cleaner.)  But I'm pretty sure that the reason you built your own tree in the actions, as I did with FreeMarker, is mostly because JJTree is borderline unusable. The whole idea that you generate all these XXXNode.java files and then post-edit them, and presumably check them into the code repository.... (And you see projects that do this!) As you no doubt realize, the INJECT statement was something I introduced back in 2008 (!) on my first run at this to turn the automatic tree-building side into something usable.

So, I think that is basically a game changer. I tend to think that with JavaCC21, the vast majority of people would prefer to use the automatic tree-building even taking into account that it's typically not (in a first pass anyway) generating the exact tree they want. I mean, given that the tool cannot read your mind.... but I mean, whatever inconvenience we're talking about, compared to having to put tree-building code actions all over the place and having to have all these XXXNode.java files that you write (and maintain) by hand... Besides that, just the fact that you can put your `INJECT` statement for a given node at a point in the grammar very close to where that element is defined... as opposed to having people go on a wild goose chase to find where things are actually specified. Already, I think that's a huge practical productivity advantage.

But the more fundamental point, I would say, is that, finally, something is either edited by hand or it's generated. (Something that is generated and then subsequently edited by hand is neither fish nor fowl...) If it's generated, you don't edit the file directly and you certainly don't check it into the code repository. And a full rebuild just regenerates that file. The way you customize a generated file is via INJECT and if you absolutely had to, you could also edit the template that generates the file, but there should be little need for that in typical usage. But any use pattern that has you post-editing generated files is....

But you talk to people about this and say: Look, I fixed this whole mess, and it's like.... one just ends up dealing with such wilful obtuseness and a level of sheer cussedness from people in this overall milieu that...

Well, I'm loath to go on about it too much here, because this is a public setting and searchable. Though, I have no reason not to say certain things either. I mean, certain people have treated me, over the past year, with such a level of rudeness, such a total lack of basic graciousness that....

> 
> > But I think this question may relate to a sort of big question that has been puzzling me over the last year at least. And that question is: why are parser generator tools so under-utilized?
> 
> One reason might be that they don't make things as easy for the developer as they could be. For example, your own recent innovations do make things easier for JavaCC users, but look how long the project has stagnated before you picked it up again recently. There's no money in language development directly, really, so it's the kind of work that has to be done either for love or 

Well, what you say above is true, but  I think it's only a partial explantation. There are certain rather unpleasant aspects of this whole situation that maybe one would prefer to gloss over... I dunno, out of some sort of nice-guy-ism Zeitgeist or just because it's unseemly to whine, I guess...

Over the last year or so, I have received a few very nice messages thanking me for my work on JavaCC. On the other hand, I also ran into what I call the [Norbert Sudhaus Fan Club](https://javacc.com/2020/11/05/three-cheers-for-norbert-sudhaus/). There's a group of these people who, out of sheer cussedness basically, just refuse to acknowledge my work in this space. Like that Norvell guy I mention in that article... it's not just that he does not use JavaCC 21. He really just refuses to look at my work. And it really goes beyond that. He doesn't really acknowledge that it exists! For him and the rest of those people, JavaCC is whatever was developed at Sun in the mid or late 90's with that closed feature set that was defined over 20 years ago. And anything I have done just doesn't exist.

Well, it's a big conversation and I don't really understand the mentality of these people.  Offhand, one would think that anybody for whom JavaCC was an important tool in their toolset, knowing the state of abandonment of the thing, would just be delighted that somebody like me is doing this. After all, any longstanding JavaCC user only stands to benefit from what I'm doing. But not only do they refuse to use my work, or even to look at it, it goes beyond that. There are very strong signs that they deeply resent what I've been doing. In particular, the  main people in these projects: [JavaParser](https://javaparser.org), [PMD](https://pmd.github.io)](https://pmd.github.io), and [JSQLParser](https://github.com/JSQLParser/JSqlParser). These projects are heavily built on JavaCC and they won't even talk to me. 

It's strange. They have very litle self-awareness. If one tries to reason with them, like: *Guys, is your intention to ignore -- month after month, year after year, and eventually decade after decade -- the only real work taking place in this (JavaCC) space? Think about it. Aside from undermining your own work, using an inferior, broken tool in the full knowledge that there is a fixed version, just what kind of people do you end up looking like to any discerning observer?"*

Well, they may have made the cynical calculation that there are precious few "discerning observers" out there. But I don't think it's that. It's more like a complete lack of self-awareness. They behave in this utterly awful way -- resentful, petty, jealous... -- yet have no awareness of it. In fact, I am presumably the villain in this set piece and my villainy is basically that I want to resuscitate this old dinosaur project! (Well, I'm also a villain, I suppose, because I'm not really taking it lying down. In the above, I am naming names. The project names at least, but one can see who these individuals are, if one is at all curious...)

>in pursuit of wider goals (where there is indirect money from corporate sponsorship/investment to further those wider goals - things like TypeScript, Dart, Rust, Swift come to mind).

Well, it's true that there would surely be more progress in this space if there was more money incentivizing it. That's always the case surely.  But the relative lack of money is not a full explanation of what is going on here. It's getting into all the psychology behind what I call [nothingburgerism](https://doku.javacc.com/doku.php?id=nothingburger), which I think is a psycho-social malaise of some sort. I wrote that essay over a year ago, I couldn't honestly tell you why even, but I guess as a kind of catharsis. A couple of silicon valley veterans (one who I had known personally for over 20 years and another who I didn't know, just wrote me out of the blue) dropped me a note and said that I had nailed it on so many levels. I myself, after writing a first draft of that, reread it and asked myself why I bothered. Surely, everybody knows all this, don't they? But they never say it openly because, well, you know, they have to deal with these people every day in their day jobs, so...

So, yeah, there's the lack of money behind the work in this space, but it's also, probably more so, the prevalent nothingburgerism. But that does lead to the question of why it is such a huge problem here. I mean, there's nothingburgerism everywhere, so why is it especially chronic in this space? I actually have some tentative theories about that, but that would get too long, so.... And besides, maybe that would be better for private conversation anyway.

> > I think that a lot of people who need a parser for a complex language like Java frequently end up coding it by hand. And that is a rather strange situation since YACC came out back in 1975.

> 
> Personally, I'll take LL(k) recursive descent over LR(k) tools like YACC for many applications.

Yeah, I tend to agree, but that is a separate conversation really.  The question (one of them) is why so many projects at this stage of computing history eschew any parser generator at all (regardless of LL vs. LR vs. whatever) and then the other question is why we'd even be talking about something like YACC! Something that came out 46 years ago! How many conversations are we going to have about PDP-11 assembly language or something like that? If you're talking about computing history and such, fine, but it's not part of anybody's current-day toolstack!

<<snip>
> One never knows till one tries ...

Well, that's getting at the heart of it. One can only control what one does oneself. And so, it tends to be a waste of energy to concern oneself too much with what other people are or aren't doing. I mean, so, as regards the bitterness that I express openly above regarding the sheer cussedness of so many people in this space... well, I express it openly but it's not really my focus. I'm really just too busy with what I'm doing to focus on that sort of thing. That said, though, I'm not going to make any effort to pretend that things aren't how they are. But from my personal point of view, the important thing is not letting these people's negativity infect me and get me down. I've suffered a couple of depressive episodes in the past and I'm conscious that I need to protect myself from that kind of negativity. But the topic kind of came up naturally because I can't really agree (not fully, anyway...) that the evident stagnation in this space is attributable solely to a lack of money. I think that an honest discussion of the situation would say that, yes, there is that as a factor, but there is also this weird malaise. So you see as a result, that somebody like me can show up on the scene and pick up this JavaCC, rewrite it in a rational way, fix every longstanding bug, add needed new features, and these people will, by and large, just decide to pretend that this work I've done does not exist! But I'm satisfied that this is a characteristic of this dysfunctional milieu. It's not about me, Jon Revusky, as a person. They'll try to frame it that way, of course, but nobody who showed up in this space and tried to do what I've done would have very different results in terms of getting these people to adopt their work. The difference between me and other people in this instance is mostly this kind of weird stubborness on my part. Most people would somehow "get the message" that they're not supposed to try to resuscitate something like JavaCC and just drop it. And I've decided, particularly this time round, not to "get the message".

So, the bottom line is that the first time round, specifically circa 2008, I let these people completely undermine me psychologically, psychically.... and this time, I'm not letting it happen. It's like my psyche has generated antibodies and I have immunity. (At least I feel like I do, but that admittedly remains to be seen! :-))

Oh, by the way, I just noticed that a google search for "Norbert Sudhaus" gives my blog article as the first hit! So maybe I will finally fulfil my ambition of creating a widely used internet meme!

**Comment by vsajip** [comment]
> Now, granted, it's wasteful in terms of memory to store every last comma if you don't need it

Memory use is not a concern - it's more about how it's more work to get to the bits that matter.

> In any case, the generated parsers are quite fast.

This might not be true for parsers in Python, though. I fear they may be slower, but let's see how much.

> True, but again, in the general case, we don't know what the person is trying to do.

I'm not saying that the parsers that JavaCC generates in general should behave differently in terms of tree generation. I'm talking about the Java grammar that is used internally - while it's currently the same as the example grammar, there's no reason why it has to be. For example, we could augment an internal grammar with AST constuction (leaving the CST stuff as it is) using classes useful to JavaCC (e.g. for code generating/transpiling to different languages) but they would be of limited pedagogical interest, so there's no need to have them in the examples Java grammar.

> He really just refuses to look at my work [...] These projects are heavily built on JavaCC and they won't even talk to me.

You could reciprocate - "They're dead to me" :wink: 

> And so, it tends to be a waste of energy to concern oneself too much with what other people are or aren't doing

My sentiments exactly, unless you have worked with those people and have some sort of working relationship with them. Plus, as it's all volunteer time, who are we to set anyone else's priorities?

> need to protect myself from that kind of negativity.

One has to do [the Harold Arlen thing](https://en.wikipedia.org/wiki/Ac-Cent-Tchu-Ate_the_Positive), in my view. While there's work on the table, neat things to create and interesting problems to solve, there's no need to look at anything else in the work-related sphere.

**Comment by revusky** [comment]
> > Now, granted, it's wasteful in terms of memory to store every last comma if you don't need it
> 
> Memory use is not a concern - it's more about how it's more work to get to the bits that matter.
> . 
> > In any case, the generated parsers are quite fast.
> 
> This might not be true for parsers in Python, though. I fear they may be slower, but let's see how much.

Well, I think it will be quite a bit slower. The benchmark I just told you about, it taking about 40 seconds to parse all of JDK 16. If you run the same benchmark with -Xint (i.e. just interpreted Java, no JIT compilation) it takes about half an hour! So without JIT compilation, it's about 45 times slower maybe.

I hope Python turns out to be a bit better than that but I get the feeling it might not be. I'm subscribed to the antlr mailing list and, on a couple of occasions, somebody said that the Python target is roughly 30x slower than the Java target. But that is, I guess, still within the range of performance of the interpreted Java. Actually, if you run it on smaller amounts of input (which would be more typical) then the speed difference is less, because there is the whole issue of startup time and the JIT compiler sort of warming up... you know... But I think it's bound to be 20x slower in just about any case, I daresay. So my best guess would be that python performance is likely to be something in that range, like 20 to 40 times slower maybe....

But even 50x slower is fast enough to be useful for many use-cases. I mean, the current Java parser can parse maybe about 100,000 lines a second. Even parsing just 2,000 lines a second would still be fast enough for plenty of utilities and so forth. And then the point is that if it really is just not fast enough, you can switch to a faster language, like Java, without too much fuss. So it all just gets back to the concept that you can use Python for rapid prototyping and then if you do need it to be a lot faster (which you frequently don't!) then you haven't painted yourself into a corner -- as opposed to if you were using a parser generator that could *only* generate Python code...

Well, as I said, I'm totally psyched about this because the whole overall proposition seems very attractive.

> 
> > True, but again, in the general case, we don't know what the person is trying to do.
> 
> I'm not saying that the parsers that JavaCC generates in general should behave differently in terms of tree generation. I'm talking about the Java grammar that is used internally - while it's currently the same as the example grammar, there's no reason why it has to be.

Well, yeah, that's actually a valid point, yes. But the fact does remain that, as long as you have a CST you can, at least in principle, convert that into any AST you want, because you're not throwing away information.

But, actually, here is [a blog article I came across a while ago](https://mortoray.com/2012/07/20/why-i-dont-use-a-parser-generator/). That is from nearly a decade ago, but I somehow doubt that his views have changed all that much given the slow progress in this space. I just reread that, and I think JavaCC21 does actually address a fair number of his gripes already, like the inability to tokenize according to context, and certainly his gripe about location information is not applicable to JavaCC 21. The issue of the resulting syntax tree not being what one wants is mentioned and that remains, I grant. But I don't know what the general solution to that really is.

> For example, we could augment an internal grammar with AST constuction (leaving the CST stuff as it is) using classes useful to JavaCC (e.g. for code generating/transpiling to different languages) but they would be of limited pedagogical interest, so there's no need to have them in the examples Java grammar.
> 
> > He really just refuses to look at my work [...] These projects are heavily built on JavaCC and they won't even talk to me.
> 
> You could reciprocate - "They're dead to me" 
> 
> > And so, it tends to be a waste of energy to concern oneself too much with what other people are or aren't doing
> 
> My sentiments exactly, unless you have worked with those people and have some sort of working relationship with them. Plus, as it's all volunteer time, who are we to set anyone else's priorities?

Well.... yeah, that argument can be made but finally, I think it can be problematic. You see, the fact remains that there is a basic *value proposition*, let's say, in open source. (Or multiple value propositions, maybe...) But, just at the most basic level, you run into an issue and fix it or improve it in some way and you give your improvement back that to the project and then everybody gets the benefit of what you did. That's the basic value proposition and when people are behaving in a way that totally undermines that value proposition.... 

Or to put it another way maybe... there is a value proposition that, for it to work, requires that people behave in a certain way that meets a certain standard... So when people's behavior does not meet that standard, then what? Well, you recognize that you can't do much about it, but I think there is this need to transcend the dominant "I'm okay, you're okay" ethos and to be willing to say matter-of-factly that these people's behavior does NOT meet certain minimal standards. Now, specifically, in this case, we have the fact that I've done all this work and hardly anybody is getting the benefit of what I did (yet...). And that's through no fault of mine. There's no other way to deal with that sort of [nothingburger](https://doku.javacc.com/doku.php?id=nothingburger) situation than to do what I did, but it's utterly sub-optimal. Really, in any sane world, it should have been possible for me to do this work within the established JavaCC project. There was never any technical need for a "fork" because a fork is a "bifurcation" of effort, but there is no bifurcation, which would be them doing something and me doing something. It's just me doing something and them doing nothing, so....

But, okay, of course, I intend to pretty much entirely concentrate on what I do, but I'm not going to pretend that I don't find certain people's behavior totally deplorable and unacceptable. (Even if I can't do much about it, which is still another question....) So, I guess my position is that I'm not going to pretend (either to the outer world or to myself internally) that I don't utterly resent these people, but no, I'm not going to let those feelings completely overwhelm me or anything.

And really, finally, the bottom line is that nothingburgerism is basically a specific subcase of assholery. (I mean, why mince words about this?) What is it to be sitting on some well known project like a JavaCC, and year after, producing absolutely nothing, no real roadmap for future development, and then making life impossible for somebody who actually does want to do something with the thing? It's some sort of form of assholery for sure.

> 
> > need to protect myself from that kind of negativity.
> 
> One has to do [the Harold Arlen thing](https://en.wikipedia.org/wiki/Ac-Cent-Tchu-Ate_the_Positive), in my view. While there's work on the table, neat things to create and interesting problems to solve, there's no need to look at anything else in the work-related sphere.

Well, I guess I mostly agree. There may be some nuanced disagreement, but.... it doesn't really matter. :-)

**Comment by revusky** [comment]
In the last day or two, I refactored teh Java grammar to get rid of that PrimaryExpression construct. I think the resulting tree should be more intuitive to work with. https://github.com/javacc21/javacc21/blob/master/examples/java/Java.javacc#L664-L697

In any case, you can run the little JParse test harness in examples/java on a single source file to see what the tree for a give source file looks like. Certainly all feedback is very welcome!

**Comment by vsajip** [comment]
Yes, it's definitely more intuitive, thanks! I have already written some tree transforming code which removes e.g. punctuation tokens from the CST when creating the transformed tree. I think without `PrimaryExpression`, footguns in my code should be fewer :slightly_smiling_face:

**Comment by vsajip** [comment]
Hmmm ... it seems like `PostfixExpression` is just like `PrimaryExpression` used to be - here's a screenshot of a CST:
![ss2](https://user-images.githubusercontent.com/130553/125810625-2e7ec308-c7b0-4f56-914a-807c53e60374.png)
Things seemed to have improved (hence [my comment](https://github.com/javacc21/javacc21/issues/73#issuecomment-879430650)) so I'm not sure if this is a regression. This makes the tree harder to navigate - which means that while the grammar is successfully parsing everything you throw at it, the resulting tree is harder to use than it should be.

**Comment by revusky** [comment]
I'm confused by your graphic above. The node corresponding to getChild(1).toString() should not be an instance of PostfixExpression. The PostfixExpression production should only create a node if there is more than one (i.e. two in this case) items on the tree-building stack. Or IOW, we should only have a PostfixExpression node if there was a ++ or -- after an expression.

**Comment by vsajip** [comment]
Let me double-check that I'm using the expected version of the Java grammar, then.

**Comment by vsajip** [comment]
Oof - I think it was to do with having an old bin/javacc.jar - the problem seems to have gone away, once I ensured that I started with the latest checked-in `bin/javacc.jar`, after which `ant full-test` was fine. Sorry for the noise.

**Comment by vsajip** [comment]
I'll close this, as I have now implemented tree transformations which obviate, or at least mitigate, the problem.
