### ISSUE TITLE
AST Node generation - something isn't clear to me, can you please enlighten me?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#76]
I'm looking at how AST nodes are generated. According to the headers of numerous files, they are generated from the `ASTNode.java.ftl` template. From this bit in the template,
https://github.com/javacc21/javacc21/blob/b267b84ea782e4761c47235cac0f4ebbe0908ef9/src/ftl/java/ASTNode.java.ftl#L60-L63
I can sort of see how it generates this code for e.g. `ArrayInitializer.java`:
```java
@SuppressWarnings("unused")
public class ArrayInitializer extends BaseNode {
}
```
though it's a little puzzling that the closing brace is on the next line - is it because of `JavaFormatter` processing? More puzzling is this in e.g. `Expression.java`:
```java
abstract public class Expression extends BaseNode {
    public boolean isMethodCall() {
        return false;
    }
```
Where is the logic for inserting the injected class members? Also, from e.g. `EqualityExpression.java`, 
```java
@SuppressWarnings("unused")
public class EqualityExpression extends Expression {
}
```
how does the injected superclass get into the generated file? I can't see how that happens from `ASTNode.java.ftl` - what am I missing? I can probably figure it out, but I also figured that it'll be quicker if you can give me a pointer.

**Comment by revusky** [comment]
> though it's a little puzzling that the closing brace is on the next line - is it because of `JavaFormatter` processing?

Yes, that's where the extra newline is getting inserted. All the source files generated by templates go through that. Of course, it's hardly necessary in this case, but if you didn't have that, the more complex templates would output things like:

     if 
     (
            x==y
            &&
            y==z
     )

Actually, worse than that because it wouldn't be properly indented typically at all. But the general problem is that a template that is nicely formatted does not typically produce source code that is nicely formatted. 

 More puzzling is this in e.g. `Expression.java`:
> 
> ```java
> abstract public class Expression extends BaseNode {
>     public boolean isMethodCall() {
>         return false;
>     }

> ```
> 
> Where is the logic for inserting the injected class members? Also, from e.g. `EqualityExpression.java`,
> 
> ```java
> @SuppressWarnings("unused")
> public class EqualityExpression extends Expression {
> }
> ```

Well, I guess you understand that this is coming from here: https://github.com/javacc21/javacc21/blob/master/examples/java/Java.javacc#L447-L480

But I guess what you mean is where the machinery is to get it into the generated files, right?

> 
> how does the injected superclass get into the generated file? I can't see how that happens from `ASTNode.java.ftl` - what am I missing? I can probably figure it out, but I also figured that it'll be quicker if you can give me a pointer.

Well, the key class to look at is here: https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/java/CodeInjector.java

And the other key point is here: https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/java/FilesGenerator.java#L195

All this, by the way, might explain why I have been pretty adamant that we have to be able to parse Python code. Because we want the same capability to inject code. Well, there might be some kludgy way of doing this without having the AST, but I think it ends up being not just more elegant when you really can parse the code, but also finally *easier*.

**Comment by vsajip** [comment]
> But I guess what you mean is where the machinery is to get it into the generated files, right?

Indeed, and thanks for those links, I will investigate those areas.
