### ISSUE TITLE
Possibly different behaviour of Java parser when used inside JavaCC?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#79]
I noticed something a little odd, which I haven't quite got to the bottom of - perhaps you can help. If I parse a particular statement using the example Java grammar, I get this CST:

```
$ jython parse.py --kind stmt "return childrenOfType(ObjectType.class);"
<ReturnStatement (1, 1)-(1, 40)>
  return
  <PrimaryExpression (1, 8)-(1, 39)>
    <Name (1, 8)-(1, 21)>
      childrenOfType
    <InvocationArguments (1, 22)-(1, 39)>
      (
      <PrimaryExpression (1, 23)-(1, 38)>
        <ClassLiteral (1, 23)-(1, 38)>
          <ObjectType (1, 23)-(1, 32)>
            ObjectType
          .
          class
      )
  ;
```
However, when parsing this same thing inside JavaCC, i.e. using the included Java parser, I get a slightly different result. Here's the relevant screenshot from a debugging session (quickest way to show just this part of the parse tree):
![Partial parse tree](https://user-images.githubusercontent.com/130553/125036325-c7600700-e08a-11eb-9f41-9605a4247b2f.png)

As you can see from the bit highlighted in red, the CST doesn't contain a `ClassLiteral`, but rather a `ReturnType`. I can't recall this happening before, but I've recently synced with your recent changes. Could there be a change in behaviour in this area?

**Comment by revusky** [comment]
Hmmm. On first reading of this, I was a bit perplexed. It didn't make any sense to me. But I think the only possibility is that, in the two cases, you're not using the exact same Java grammar. That would be because, when you build the javacc.jar, it is actually getting the Java.javacc file out of the *bootstrap* javacc.jar in the bin directory. That's what the `INCLUDE JAVA` on line 449 of `JavaCC.javacc` is saying. So, to test that hypothesis, I guess you could do one of two things:

- Change the `INCLUDE JAVA` to `INCLUDE "../../examples/java/Java.javacc"`
- Do a "local rebootstrap" (I guess that would be the terminology) i.e. copy the javacc.jar you just built into the bin directory and rebuild again.

I hope that's the issue, because otherwise it is a real mystery. I was mucking with the Java grammar a bit, but I can't think what change I made that would have changed the tree, but it's the only explanation I can find. I've been vaguely aware that there was a possible issue with this. I changed the INCLUDE statement mostly just to exercise this sort of feature, of having canonical includes, like I could anticipate fairly soon that `INCLUDE PYTHON` would just be a shorthand for something like `INCLUDE "/include/python/Python.javacc"` and if it doesn't find it on the file system (which it basically never will!) it fishes out of the jarfile, i.e. loads it from the classpath. The underlying assumption, I guess, is that the "canonical" grammar files in the jarfile don't change very much. A little bit now and then but should be pretty stable over time. As the project matures, i guess... :-) 

Anyway, I haven't checked but the above is the only explanation I can come up with, but it should be pretty easy for you to verify that this is in fact the issue.

**Comment by vsajip** [comment]
I think you've got it. The issue went away after I copied `javacc.jar` into `bin`. Things probably got a bit messed up when I rebased your recent changes - source files were fine, but of course `javacc.jar` is pretty much opaque as far as Git is concerned.
