### ISSUE TITLE
Odd behaviour of Python lexer - skipping tokens?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#83]
For some reason, the Python lexer appears to be skipping tokens - not sure what's happening. I modified `PLex` to print out each token's type, image, and beginning/end positions. When I run this modified `PLex` on a test file in the standard lib,

https://github.com/python/cpython/blob/05162993fe62e7fa3acebdd0062586b9bf63d46a/Lib/test/test_venv.py#L24-L27
which is just (starting at line 24)
```python
try:
    import ctypes
except ImportError:
    ctypes = None
```
I get this sequence of tokens printed:
```
TRY: try 24 1 24 3
COLON: : 24 4 24 4
NEWLINE: 
 24 5 24 5
INDENT: INDENT 25 1 25 4
NAME: ctypes 25 12 25 17
NEWLINE: 
 25 18 25 18
DEDENT: DEDENT 26 1 26 0
NAME: ImportError 26 8 26 18
COLON: : 26 19 26 19
NEWLINE: 
 26 20 26 20
INDENT: INDENT 27 1 27 4
ASSIGN: = 27 12 27 12
NONE: None 27 14 27 17
NEWLINE: 
 27 18 27 18
```
I would have expected tokens for the `import` on line 25 before the `NAME: ctypes`, the `except` on line 26 before the `NAME: ImportError`, and the `ctypes` before the `ASSIGN` on line 27.

Is there something special about tokens immediately following `INDENT` /  `DEDENT`? Why aren't they being printed? Of course the parser runs fine on these files so I imagine  the tokens aren't actually being lost, but this result seems confusing ...

**Comment by vsajip** [comment]
OK, I think I see the issue - e.g. the INDENT token has a `next` token, but that means that naively calling the lexer's `getNextToken()` will seem to skip tokens. You have to follow the `next` chain of any returned token before calling `getNextToken()` again. Is this documented somewhere? It certainly doesn't seem to happen for e.g. the Java lexer.

**Comment by revusky** [comment]
> OK, I think I see the issue - e.g. the INDENT token has a non-null `next` token, but that means that naively calling the lexer's `getNextToken()` will seem to skip tokens. You have to follow the `next` chain of any returned token before calling `getNextToken()` again. Is this documented somewhere? It certainly doesn't seem to happen for e.g. the Java lexer.

Yeah, it seems that PLex is not much of a test harness really. (Nor is JLex, which it is based on!) I guess I mostly wrote JLex just to have a benchmark of how fast it can tokenize. It really should check whether any given Token is instanceof InvalidToken, because otherwise, it just always succeeds! So it's not much of a test. LIke, with tokenizing Python code, it generates an InvalidToken instance if the indent/dedent spacing is wrong. But it's not even checking for that.

> You have to follow the next chain of any returned token before calling getNextToken() again. 

Yeah, I guess so! The whole thing is overly intricate and complicated and it evolved in a certain way from what was there originally. For one thing, now that the Token class is retrofitted to implement Node (at least assuming that tree-building is on) then there is this whole sort of Pandora's box regarding the possibility that the next token wrt token chaining is possibly different from the next token in terms of tree traversal logic. Like, suppose you inject an element into a Node, then the token chaining logic, just going via token.getNext() is going to skip over the tokens in the element you just injected. Stuff like that... I mean to say, the whole thing is very complicated and, at some point, I think there will be a need to sit down and just redesign the whole thing maybe. And that might involve some backward incompatibilities, at least in terms of doing very intricate things... The whole thing is kind of scary even...

For example, the JavaFormatter class gets the stream of tokens by traversing the tree, but at some point, I thought I could simplify it by using the token chaining and it took me quite a while to realize that thjs didn't work because the token chaining is broken wrt injected nodes.

>Is this documented somewhere? It certainly doesn't seem to happen for e.g. the Java lexer

Uhh, I have to admit that this stuff is not sufficiently documented *anywhere*. (In legacy JavaCC, with this horrific specialToken stuff, that was never really very well documented either!) And, truth told, it might not be worth documenting at the moment, because it would probably be better to expend the energy clean the whole thing up and *then* document that! But that could be a very big backward incompatibility nightmare. But still, there are not so many end-users. Yet... So.... 

But anyway, I could go on about this, but the current state of affairs is that I really hate all this token chaining. It is terribly error-prone generally. Using it to insert extra tokens in the chain, as I do with the INDENT/DEDENT mechanism really requires too much knowledge of internals. And even with my knowledge of the internals, it was hard for me to get it right!

**Comment by vsajip** [comment]
Oof. I feel you - that stuff has always felt rather gnarly. The approach I've generally used (for both tokens and chars in the lexer, for stuff I've written by hand) is to use a pushback buffer. Code that needs to get stuff checks the pushback buffer, doing the real get when the buffer is empty. Code that needs to insert stuff just inserts it into the buffer. I never use `previous` and `next` fields in tokens. It just feels like an accident waiting to happen.

**Comment by revusky** [comment]
> I never use `previous` and `next` fields in tokens. It just feels like an accident waiting to happen.

Yeah... my gut sense on this is that your instinct was correct. The whole thing is currently something of a mess. I have been thinking over the last day if we could see our way clear to getting rid of the token chaining, possibly just having a LEGACY_TOKEN_CHAINING setting that keeps it there if you're depending on it. 

Now, as I recall, legacy JavaCC never had a `previous` field in the generated Token class. It had something called specialToken, which was the previous *unparsed* token (typically a comment in practice) and the specialToken potentially had its own chaining, so you could have token.specialToken.specialToken. So the way you'd get preceding comments is that you'd iterate back through the specialToken fields and then when you hit null, you'd reverse the order of the special tokens to get them in the order they actually appeared. Something like that.

One thing about all that the whole concept is screwy. From the POV of the tokenization machinery, there really aren't two kinds of token, parsed and unparsed. There are just tokens. It's the job of the higher level parsing/tree-building machinery to turn this stream of tokens into an AST. But, in principle, the tokenization "machine" does not even need to "know" which tokens participate in parsing or end up inside the AST or whatnot. Or, I mean, the thing is built in layers, and tokenization is a lower layer that just produces a stream of tokens and is not concerned with the parsing details.

So, from the POV of the tokenization machinery, ideally, there is no distinction between parsed and unparsed tokens. (That is the concern of the parsing machinery.) However, there is a real distinction between regular or *physical* tokens, i.e. that really correspond to some location in the physical file, and *virtual* (or *synthetic*) tokens, o.e. things like INDENT, DEDENT, or EOF.

Well, the above are some wooly-minded thoughts, but there is a more basic point I would make about all this: I don't think we should bring any legacy baggage with us to a PythonCC. In terms of python-related usage, we have pure blue skies at the moment. No BWC issue. So we should just try to design the best API for all of this possible. And it may well be that we can just get rid of all this token chaining. Eventually the Java side would adopt the clean redesigned API and (optionally) keep the older token chaining working with a setting. (Even then, I am wondering about jumping through too many hoops to keep JavaCC21 backward compatible with legacy JavaCC. Based on my experience of the last year or so, BWC with legacy JavaCC is actually of fairly little practical value. It now seems quite obvious that pretty much all adoption of the tool will be from new users.)

So that's my idea. I think that, generally speaking, the upcoming PythonCC should not carry over kludgy baggage that originates in the legacy tool -- or even design mistakes in JavaCC21. I think we should seize the opportunity to really start PythonCC with a very clean design. You see my point, right? Surely you agree, no?

**Comment by vsajip** [comment]
> there really aren't two kinds of token, parsed and unparsed. There are just tokens

Indeed.

> I think that, generally speaking, the upcoming PythonCC should not carry over kludgy baggage that originates in the legacy tool -- or even design mistakes in JavaCC21. I think we should seize the opportunity to really start PythonCC with a very clean design. You see my point, right? Surely you agree, no?

Definitely something to aim for!

**Comment by revusky** [comment]
By the way, another thing that I dread more than fixing the token chaining is this whole INCLUDE mechanism. It just has the problem that there is no namespace disposition. So you can't really write a grammar file that can be generally INCLUDEd from another file with any confidence that the names of tokens and productions won't clobber one another.

Finally, I think there's a need for a separate IMPORT instruction, something like `IMPORT "Python.javacc" as Python` and then anything in the INCLUDEd grammar (from the INCLUDEing grammar) would be specified with the prefix, like `Python.Block` or something. I think the way to do it would be via inner classes. But it's something complicated that I think I'll have to deal with at some point soon. If we need to be able to include the grammars for more than one language, it doesn't seem practical for all the production names to be unique.

**Comment by vsajip** [comment]
> Finally, I think there's a need for a separate IMPORT instruction, something like IMPORT "Python.javacc" as Python and then anything in the INCLUDEd grammar (from the INCLUDEing grammar) would be specified with the prefix, like Python.Block or something.

Yes, that would be useful, and will also perhaps remove the need for the preprocessor token-name hacks where you have to prefix with `PP_` as a sort of poor-man's namespace.

**Comment by revusky** [comment]
I think I can close this whole issue since the stuff I was talking about, i.e. fixing token chaining actually got done a few months after this. So effectively, the whole discussion is obsolete. I do find it kind of satisfying to read through, because it shows this record of setting certain goals and accomplishing them -- in this case, fixing the token chaining.

In any case, I'm going to close this issue as well.
