### ISSUE TITLE
Any particular reason that chars under 10 are displayed as decimal, all others as hex?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#87]
https://github.com/javacc21/javacc21/blob/485baa3697f67d2c040aef98f749278ac72b42ca/src/java/com/javacc/Grammar.java#L1242-L1243

The reason I ask is that in Python, some slight post-processing of the return value needs to be done - so I'd like to merge these two cases.

**Comment by revusky** [comment]
Well, the only reason for this displayChar method is to be able to generate somewhat more readable code. I prefer to generate something like:

              if (ch >= 'a' && ch <='z') {...}

than to have:

              if (ch >=97 && ch <= 122) {...}

Because the first one is clearer to a human reader. And I prefer to generate:
 
              if (ch=='\n') {....}

instead of:

               if (ch==0xA) {...}

It doesn't really make that much difference though. As for that specific case of `if (ch<10)` that's just a little afterthought that there is no need to write 0x8, say, since it's the same thing as just 8. If you removed that line, everything would work the same. The whole thing is not of very much importance really. 

Well, to answer your question about there being any particular reason for that, it's just some slight aesthetic adjustment really. Nothing very important.

**Comment by vsajip** [comment]
OK, that's fine. I understand why `displayChar` is there, just not the reason for displaying `8` vs. `0x8` for chars in the range ASCII `NUL`-`TAB` (in fact, `TAB` itself is handled as a special "for readablity" case along with `CR`, `LF` etc. in the same routine).

In Python, any char that is not displayed as 'X' (e.g. 0x8, 8, 0x167f etc.) needs to be displayed using a helper function `as_chr` such that it becomes `as_chr(8)`, etc. in the Python source. This is so that comparisons with chars work correctly.

So, it seems I can just replace the above two lines with

```java
s = "0x" + Integer.toHexString(ch);
if (Grammar.this.codeLang.equals("python")) {
    s = String.format("as_chr(%s)", s);
}
return s;
```
to get the desired behaviour.
