### ISSUE TITLE
Add `find` methods in generated `Node`

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#9]
Generated Node interface provides `getParent()`, `getEndLine()`, but it should be very cool if it could provides other methods like:

 * `getFirst()` : returns the first node of the node children.
 * `getLast()` : returns the last node of the node children.
 * `findNodeAt(int line, int column)` : returns the node at the given position otherwise the node (this).
 * `findNodeBefore(int line, int column)` : returns the before node from the given position.
 * `findNodeAfter(int line, int column)` : returns the after node from the given position.

Those methods should be implemented in the generated BaseNode.

**Comment by revusky** [comment]
I agree that it makes sense to have commonly useful methods right there available in the BaseNode implementation. However, you may (or may not) be aware that there is a feature called "Code injection" that allows you to insert a useful little routine right there in the grammar file. See: 

https://doku.javacc.com/doku.php?id=code_injection_in_javacc_21

That is actually the only page in that DokuWiki instance! I just added it. It was here before:

https://github.com/revusky/freecc/wiki/Code-Injection

I've got to move all these pages over. Not that, even then, everything is so well documented.

But anyway, if you need some routine in your Nodes, you can just write something like:

INJECT(BaseNode) : 
{}
{
    public Node lastChildOfType(Class clazz) {
        Node result = null;
        for (Node child : children()) {
            if (child instanceof clazz)
                    result = child; 
        }
        return result;
    }
}

Well, I guess the above would provide a warning since one is supposed to use Generics, but I think it works. So then you could just have lastChildOfType(Text.class) in your code and it would return the last Text child node. (Or null if there is none.)

But, I agree that it makes sense to have generally useful stuff like this just inserted by default. Actually, you can see the FreeMarker template that generates that BaseNode class here:

https://github.com/javacc21/javacc21/blob/master/src/templates/java/BaseNode.java.ftl

Another possibility, by the way, is that if you just put your own BaseNode.java.ftl file in the same directory as the grammar file, it will use that, so you could insert the extra method there. But, I think that for short and sweet little methods, the code injection approach is the most elegant. I don think that most people will want to maintain their own versions of the templates like that one. Still, even that is better than post-editing generated files, which is not a good idea. Once you decide that BaseNode.java or whatever Node subclass is just generated, you have a much better situation if you just do a clean build by wiping all those files and regenerating them. However, if you generate the file and post-edit it, then... well... you see that is a problem. It doesn't quite work!

**Comment by angelozerr** [comment]
Thank a lot for your great explanation. But I think we should have commons methods like w3c DOM node have (we have getParent, so why not having getFirst, getlast, getSiblingNode, etc).

The findNodeAt is very helpful and I think it's a good candidate for commons method. We must have a clean Node API with Javadoc.

**Comment by revusky** [comment]
Oh, don't misunderstand me. I completely agree that we need a better default Node API. What there is now is kind of the result of starting with what the legacy JJTree tool generates and adjusting forward from that. That API was created maybe in 1997, long before there was generics in Java.

Actually, you know, even leaving aside generics, I think that 1997 predates the introduction of inner classes. Also, that is before the 1.2 collections classes, so when I first got into the JavaCC code, it was all Vector and Hashtable.

Still, I feel I've addressed what is the most evil aspect of the legacy JJTree tool, which is this tendency to generate ASTXXX.java classes and then post-edit them. I feel that if a sourcefile is *generated*, then you don't post-edit it. The problem is that sometime you need to stick in a little bit of code in the generated files, so there is the disposition to do it. 

So, yes, there is a need to straighten out the whole Node API, but I was just telling you that, meanwhile, you can "inject" any helper method that you need. And, actually, if you really had to inject a lot of code in your nodes, you can do something like:

<pre>
   INJECT(TextNode)  :
   { 
        extends AbstractTextNode;
   }  { }
</pre>

And then you create your own intermediate AbstractTextNode.java that extends BaseNode, but that is not *generated* code! But then any methods you put in there are available from the TextNode subclass.

Come to think of it, that would probably be preferable if you have a very large amount of code to inject, because then you can maintain that file in your IDE. It might become clumsy to inject a lot of code inside your grammar file because you would just be editing it in a plain text editor. (Until there is tooling for this!)

But, if it's just a question of sticking in a getter/setter or something, then I think that putting the code in the grammar next to where the element is defined would be the best thing.

But, look, what we can do is simple enough. You write the helper methods you need and then when it is pretty clear that something would be generally useful, we just add it to the BaseNode.java.ftl template and it's there by default. In general, the most obvious sorts of helper methods for traversing a tree of nodes should just be there by default, I suppose. It doesn't make sense for a thousand different people to be writing their implementation of getNextSibling() or whatever.

**Comment by angelozerr** [comment]
Ok @revusky I will try to do some PR to add those find methods.
