### ISSUE TITLE
Suggested rename of production

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#91]
I suggest that the `PythonFile` production be renamed to `Module`, as this is the common terminology in Python for a compilation unit.
https://github.com/javacc21/javacc21/blob/48a950db745ec426db90c48060faca057445446d/examples/python/Python.javacc#L25

**Comment by revusky** [comment]
Well, that's not a problem. You can just go ahead and do that directly.

**Comment by vsajip** [comment]
I just noticed that I can't trivially rename it to `Module`, because the node names in the generated parser are unqualified and this causes a clash with `java.lang.Module`. What's the best way to fix this? Obviously in general this clash could happen for a number of identifiers.

**Comment by revusky** [comment]
Well, I guess PyModule might be okay. We have PyList because I was running into a clash with java.util.List.

**Comment by vsajip** [comment]
I'll do that (`PyModule`) for now, but there should probably be a better way of avoiding such clashes ... using fully-qualified class names seems overkill, though, as it will definitely clutter the generated source. Maybe use partially-qualified node names such as `ast.Module`?

**Comment by revusky** [comment]
Well, if it's a question of the node class name and the production name being different, so that the production is Module but the node is ASTModule, then that can be done. In fact, legacy JJTree actually did that! They used a prefix (that you could configure) to prefix all the generated node classes. By default it was (and is) "AST". I think NODE_PREFIX is still an option that should work in JavaCC21. So, now, the prefix is just the empty string *by default*. Or, in a specific case, you can just write the production as:

                Module#ASTModule 

I always thought the ASTXXX stuff was ugly and would tend to just use the same name for the node class as for the production. At least by default. I figure that if you have a name clash you can always rename that specific node.

At some point not far off there is going to be an IMPORT instruction, which would be an improved INCLUDE, where you might write:

      IMPORT "Python.javacc" as PY
      IMPORT "Java.javacc" as JAVA

And then I anticipate some name mangling to avoid clashes, so that internally, the `Module` when imported would get turned into `Module$PY` or something like that. But you could refer to it as `PY.Module` in the importing grammar as well. It's maybe not too hard. It would involve some traversal of the tree as a final step to fix-up the names, I guess. So I'm thinking that if you import both the Python grammar and the Java grammar, and both have a `Block` you can distinguish them via `PY.Block` and `JAVA.Block`. Some details to work out, but it is on the drawing board...

**Comment by vsajip** [comment]
OK. Just remember, `$` is disallowed in Python identifiers, so as long as it's easy to generate the mangled identifier in a language-friendly way ...  I currently do that  for Python by adding/changing methods in `Grammar.java` to generate these identifiers, e,g. a token hook method becomes `tokenHookΣPythonLexer_javaccΣ21Σ18` in Python. The methods use a  `codeLang` field in `Grammar` which is set to `"java"`, `"python"` etc. based on the command-line `-lang` argument.

**Comment by revusky** [comment]
Well, it's a very very superficial problem. You can see that in the 8 methods here: https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/core/Expansion.java#L358

It's easy enough to find where these things are used in the corresponding templates. For example, you can see where the getScanRoutine() is used: https://github.com/javacc21/javacc21/blob/master/src/ftl/java/LookaheadRoutines.java.ftl#L158 Also lines 188, 206, and 459 in that file. All these places that use '$' to generate a method name could use some other character or naming system. I generate names that include location info, you probably noticed. LIke `if (scan$Java_javacc$59$5()` so it's pretty easy to find the point in the grammar file that the scan routine corresponds to.

But that's a tangent. The point is that there is really nothing special about '$' It's just that I guess it is very typical of generated code in Java. In fact, that is how inner classes are implemented. Foo$Bar sort of thing. And I guess that, even though nobody says so, it's kind of tacitly understood that you don't use '$' in hand-written code. By convention... though one can...

But, as I say, it's a very superficial problem because we could use another character and we've got all of Unicode to work with.
